### ISSUE TITLE
Install Loop

### ISSUE THREAD

**Issue by 1amr00t** [fireeye/flare-vm#10]
The install appears to finish and start over repeatedly on Win10x64 fully updated.  Each piece of software reports it's already installed and it's forcing reinstall.  What can I provide to illuminate any issues?  Is there a log created?

**Comment by javier-lethe** [comment]
Same problem here.

**Comment by suwitcham** [comment]
Same issue on both Win7 and Win10

**Comment by Chiggins** [comment]
Started to run into this recently as well. Windows 10 x64 enterprise.

**Comment by iphelix** [comment]
There is a bug in the current version of Boxstarter where it forces to reinstall of all packages in the installation script. The behavior triggers when the reboot occurs after certain packages are installed (e.g. powershell). However, the installation process should still proceed and complete even if it has to force reinstall packages.

**Comment by urain** [comment]
Users are reporting an install loop with Fully licensed Windows 10 x64; Virtualbox; Host = Linux

**Comment by leandroinaccio** [comment]
The boxstarter web launcher is deprecated.

To install boxstarter in PowerShell V2:
```
Set-ExecutionPolicy Unrestricted
iex ((New-Object System.Net.WebClient).DownloadString('http://boxstarter.org/bootstrapper.ps1')); get-boxstarter -Force
```
And PowerShell V3 or newest:
```
Set-ExecutionPolicy Unrestricted
. { iwr -useb http://boxstarter.org/bootstrapper.ps1 } | iex; get-boxstarter -Force
```
In my case I needed to import the module Boxstarter.Chocolatey.psm1:
```
Import-Module C:\ProgramData\Boxstarter\Boxstarter.Chocolatey\Boxstarter.Chocolatey.psm1
```
Then:
```
Install-BoxstarterPackage -PackgeName https://raw.githubusercontent.com/fireeye/flare-vm/master/flarevm_malware.ps1
```
For me this worked!!!

References:
https://github.com/mwrock/boxstarter/issues/264
http://www.hurryupandwait.io/blog/retiring-the-boxstarter-web-launcher

**Comment by Timbosec** [comment]
Thanks @leandroinaccio! I had the same issues with the web link, but it's working fine now using the Powershell commands you provided - one small catch - your final command has a typo that took me a while to notice - should be "-PackageName"...You forgot the extra "a". :)

**Comment by leandroinaccio** [comment]
Thanks @Timbosec!
Fixed typo.

**Comment by iphelix** [comment]
Folks, thanks for all the comments. Weblauncher installation method is unfortunately deprecated. Please try the new installation method in the updated README and reopen if you still have any issues.

**Comment by CriticalSteffen** [comment]
Following the installation from the README in Win10 x64 VM on KVM, the process is stuck in a loop.

* It attempts to install `vcbuildtools 2015.4` and repeatedly fails, reboots, then starts the whole process again.
* Each time, I get a Generic MSI error, which flashes by too quick to read, and then the computer reboots and starts over.
