### ISSUE TITLE
Is it possible to disable the installation of Windows updates? & Build-in Admin Edge Problem

### ISSUE THREAD

**Issue by undiquex** [fireeye/flare-vm#101]
Hello

First: Very cool and useful project! Thank you

But: Is it possible to disable the installation of the Windows updates, for various reasons the Windows 10 version 1607 should be kept and not increased to 1804?

And you have to start the installation script as administrator, but in Windows 10 the Edge Browser can not be opened as Built-in Administrator, so there is always an error message that the Edge Browser could not be started, is there a solution?

Thanks in advance

**Comment by tankbusta** [comment]
What SKU of Windows 10 are using for FlareVM? Home, Pro, or Enterprise?

**Comment by htnhan** [comment]
Close due to inactivity.
