### ISSUE TITLE
Bypass all hash check

### ISSUE THREAD

**Issue by f1r3walled** [fireeye/flare-vm#102]
Hello, everyone,
Is there any way to change the script in order to bypass all hash checking while installing flare-vm through .ps1?
I'm getting a lot of hash mismatch while installing some tools like malscan, pestudio, etc.

Thank you!

**Comment by htnhan** [comment]
@f1r3walled 
This feature is probably not fixed. The checksum is there to make sure there is no corruption, and more importantly no malicious packages/installers make it through except from vetted installers.

**Comment by f1r3walled** [comment]
Got it! Thank you for your answer. I'm manually installing some tools that failed checksum verification.

**Comment by htnhan** [comment]
Please try to do cinst -s https://myget.org/F/flare/API/v2 to install them. We try to fix the checksum mismatch as soon as we see them.
