### ISSUE TITLE
Trust relationship error when trying trying to download boxstarter

### ISSUE THREAD

**Issue by joseph-hannon** [fireeye/flare-vm#108]
I get an error when running the `install.ps1 `as admin on a fresh Windows 7 x86 VM. The full error string: `Exception calling DownloadString with 1 argument(s): The underlying connection was closed: Could not establish trust relationship for the SSL/TL S secure channel.`

I fixed by adding the following from SO (https://stackoverflow.com/q/11696944/902766) to the start of the script:
```
add-type @"
    using System.Net;
    using System.Security.Cryptography.X509Certificates;
    public class TrustAllCertsPolicy : ICertificatePolicy {
        public bool CheckValidationResult(
            ServicePoint srvPoint, X509Certificate certificate,
            WebRequest request, int certificateProblem) {
            return true;
        }
    }
"@
[System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCertsPolicy
```

**Comment by htnhan** [comment]
Fixed in 237f87ecb516e06a47a21db00743c369119caf1f
