### ISSUE TITLE
Add idr - Interactive Delphi Reconstructor and all its plugins

### ISSUE THREAD

**Issue by Maijin** [fireeye/flare-vm#109]
Add idr - Interactive Delphi Reconstructor and all its plugins

**Comment by htnhan** [comment]
IDR is already included in Flare VM. We will work on adding the plugins.

**Comment by Maijin** [comment]
Oh wait then it's probably already there, my bad, I will recheck

**Comment by htnhan** [comment]
Close due to inactivities. Please re-open if IDR is not working as expected.
