### ISSUE TITLE
why don't upgrade x64dbg to newer version

### ISSUE THREAD

**Issue by cssxn** [fireeye/flare-vm#110]
I saw it download x64dbx from sourceforge.net  which  version built in 2017-09-12.

why not download x64dbg from the github release page `https://github.com/x64dbg/x64dbg/releases`

**Comment by htnhan** [comment]
@cssxn  Thank you for reporting this issue. I am a little behind in updating all the tools. Will get this in as soon as I can.

**Comment by htnhan** [comment]
Updated.
