### ISSUE TITLE
pestudio checksum mismatch

### ISSUE THREAD

**Issue by 3c7** [fireeye/flare-vm#114]
There's a PEStudio checksum/version mismatch. Version 8.80 gets downloaded as 8.79 and checked against SHA256 of 8.79 zip file.

**Comment by lukenormile** [comment]
I believe the hash needs to be updated again:
<img width="782" alt="image" src="https://user-images.githubusercontent.com/3102932/133296515-310afbe3-5a92-4f99-ad68-d5bbee72cc74.png">
The actual hash matches the one I see at https://www.winitor.com/download
