### ISSUE TITLE
Checksum mismatch Resource Hacker 

### ISSUE THREAD

**Issue by 2xyo** [fireeye/flare-vm#122]
Latest version of Resource Hacker is 5.1.6 - 4 June 2018.

Error:
```
...
Error - hashes do not match. Actual value was 'DE24309105F589D0C4F6D19C85D0354C0C8FFE9A2F34054AB2028B4A380C664D'.
ERROR: Checksum for 'C:\Users\2xyo\AppData\Local\Temp\chocolatey\reshack.portable\5.1.1\resource_hacker.zip' did not meet '0b1b42a3e5d97dcaa838cc492e0233ff3d0a5c6b3389327e6418cef338c75a17' for checksum
 type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
...
```
Changes since 5.1.1:

- Changes in 5.1.6
  -   Bugfix:  Commandline syntax bug (some commas required trailing spaces)
- Changes in 5.1.5
  -   Bugfix:  Comments within some resource definitions would not compile
- Changes in 5.1.4
  -   Bugfix:  Editor font preferences not being applied on restart
  -   Bugfix:  Minor buges in commandline processing
- Changes in 5.1.2
  -   Update:  Update to commandline sytax and & bugfixes

**Comment by 2xyo** [comment]
Thanks @htnhan for the feedback. 

After another `cup all`, `reshack.portable` has been updated. Now, I have 2 versions on my VM:
```
reshack.portable v5.1.6 is the latest version available based on your source(s).
resourcehacker.flare v5.1.1 is the latest version available based on your source(s).
```
According to [flarevm_malware.ps1#L193](https://github.com/fireeye/flare-vm/blob/master/flarevm_malware.ps1#L193), there is also a "flare" version of the package.

**Comment by htnhan** [comment]
Fixed.

resourcehacker.flare uses an older version 5.1.1 which is more stable.
