### ISSUE TITLE
Disable notepad++ auto update to reduce noise

### ISSUE THREAD

**Issue by htnhan** [fireeye/flare-vm#125]

**Comment by mattnotmax** [comment]
So I looked at this. There is a field to edit in the %APPDATA%\Notepad++\config.xml but this file is not created until Notepad++ is first run. Then it defaults to auto update. Too late. 

One solution that seems to work (though tested outside of Boxstarter script) is to create a dummy config.xml and copy it into %APPDATA\Notepad++ following installation. 

The line to add is:  <GUIConfig name="noUpdate">yes</GUIConfig>

It's a bit of a hack, but if your happy with this approach I'll see if I can get this to work with my fork and do a pull request?

**Comment by htnhan** [comment]
Fixed in bced4d386e18ec321a93a3e1e6d9475a8e46effa
