### ISSUE TITLE
dnSpy not installing

### ISSUE THREAD

**Issue by mgoffin** [fireeye/flare-vm#13]
I noticed it wasn't there after the install, so I tried `cinst dnspy` and it's getting a 404 trying to get to:

`https://github.com/0xd4d/dnSpy/releases/download/v3.0.0/dnSpy.zip`

This URL works, however.

`https://github.com/0xd4d/dnSpy/archive/v3.0.0.zip`

Is this an issue with the package manager? I see that their site shows 3.0.2.0 as the latest version they will attempt to install:

https://chocolatey.org/packages/dnspy

**Comment by iphelix** [comment]
Updated release URL to the build server on appveyor so the package now works. Looks like the GitHub binary was removed.
