### ISSUE TITLE
Python 2.7.13 32-bit missing pip

### ISSUE THREAD

**Issue by strictlymike** [fireeye/flare-vm#131]
FLARE-VM seems to be affected by this Python issue for 2.7.13 in which `pip.exe` does not get installed:
<https://bugs.python.org/issue30725>

I tried visiting `appwiz.cpl` and clicking `Change` to modify options and found that `pip` was unselected, however when I selected it and clicked through the MSI, it made no difference:

```
C:\>dir /a/b/s pip.exe
C:\Program Files\Python27\Scripts\pip.exe
C:\Program Files\Python37\Scripts\pip.exe
C:\Program Files (x86)\Python37\Scripts\pip.exe

C:\> REM I was hoping to find C:\Program Files (x86)\Python27\Scripts\pip.exe, but no joy!
```

It looks like the aforementioned Python 2.7.13 issue had some kind of resolution. Is there an MSI installer option we can provide that makes `pip.exe` get installed?

**Comment by strictlymike** [comment]
Ooh, or we could move to Python 2.7.15 which I see here: <https://www.python.org/downloads/>

**Comment by htnhan** [comment]
Change the issue type to enhancement. We will upgrade python 2.7.13 to 2.7.15

**Comment by htnhan** [comment]
Default python2 is now python2.7.15. Python2.7.13 is only there for pykd 32bit on 64bit systems. Closing
