### ISSUE TITLE
Access is denied (while installing python3)

### ISSUE THREAD

**Issue by malis2007** [fireeye/flare-vm#133]
Hello there! :D
i came across this issue (windows 7 home premium x86 vm) :
https://images2.imgbox.com/03/a2/PMbiYkbn_o.png

i tried running the script from internet explorer and from the "install.ps1" script, both gave the same issue.

Thanks for reading, and your help in-advanced! :D

**Comment by htnhan** [comment]
@malis2007 

I ran into a similar problem when installing something else as well. It is probably a race condition where the package try to clean up itself by deleting some files, but windows still hold the file. (similar to this: https://github.com/chocolatey/choco/issues/1633). This should be addressed by the package owner (chocolatey Python3 package). We use the public python3 package, so there is not much we can do.

I will keep this ticket open to see if there are more people experiencing similar issues. If so, we probably will create our own python3 installer package and handle the errors better.
