### ISSUE TITLE
Sysinternals Install Errors

### ISSUE THREAD

**Issue by matchstickboy** [fireeye/flare-vm#143]
Hello,
I've been having trouble getting Flare to install on a Windows 7 x86 vm.  Seems to run normally until the script reaches the Sysinternals installation step, at which point it errors out with the attached text.

I'll be happy to provide full logs if needed, but wanted to see if I was just missing a prereq, or some some other dumb mistake on my part.

Thanks in advance,

Chris
[error.txt](https://github.com/fireeye/flare-vm/files/2539364/error.txt)

**Comment by htnhan** [comment]
@matchstickboy  We recently have a major code change to FlareVM. The side affect is that we start using an environment variable to keep track of some configs, specifically: %FLARE_START% points to "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\FLARE". The environment variable is probably missing from your system.

There are two options now:

1. We recommend installing FlareVM from scratch to take advantage of the new packages and new features.
2. Manually set the FLARE_START environment variable, and reinstall sysinternal.

**Comment by h0pp** [comment]
I have checked the chocolateyInstall.ps1 downloade for sysinternals tools and it contains a typo for x86 version:

```
if (Get-OSArchitectureWidth -Compare 64) {
  $toolProcExp = Join-Path $toolPath "procexp64.exe"
} else {
  $toolProxExp = Join-Path $toolPath "procexp.exe"
}
```

$toolProxExp should be $toolProcExp, which leads to 

_2018-11-01 23:28:41,127 2924 [ERROR] - ERROR: Cannot bind argument to parameter 'targetPath' because it is an empty string._

To get the file that was deleted I used capture.bat, that should be a good add to the Flare VM.

Best regards

**Comment by htnhan** [comment]
@h0pp Thank you for debugging the issue. We have pushed a new version to fix this typo.
@matchstickboy  Please reinstall sysinternals.flare on x86 system and let us know if the issue is still there.

Thank you everyone

**Comment by matchstickboy** [comment]
@htnhan and @h0pp thank you both very much.  Install is now working perfectly.
Cheers 👍 
Please consider this issue closed (if not already done).
