### ISSUE TITLE
Issue Installing radare2.flare v2.6.0.1

### ISSUE THREAD

**Issue by anelshaer** [fireeye/flare-vm#144]
radare2.flare v2.6.0.1
radare2.flare package files upgrade completed. Performing other installation steps.
WARNING: Url has SSL/TLS available, switching to HTTPS for download
Downloading radare2.flare
  from 'https://radare.mikelloc.com/get/2.6.0/radare2_installer-msvc_64-2.6.0.exe'
Downloading radare2.flare
  from 'https://radare.mikelloc.com/get/2.6.0/radare2_installer-msvc_64-2.6.0.exe'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://radare.mikelloc.com/get/2.6.0/radare2_installer-msvc_64-2.6.0.exe'. Exception calling ".ctor" with "2" argument(s): "Could not find a part of the path 'C:\Users\Uzr\AppData\Local\Temp\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\radare2_installer.exe'."
The upgrade of radare2.flare was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\radare2.flare\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - radare2.flare (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\radare2.flare\tools\chocolateyinstall.ps1'.
 See log for details.
Chocolatey reported an unsuccessful exit code of 404. See C:\Users\Uzr\AppData\Local\Boxstarter\boxstarter.log for details.
+ Boxstarter finished Calling Chocolatey to install radare2.flare. This may take several minutes to complete... 00:00:08.8410140
+ Boxstarter finished Calling Chocolatey to install radare2.flare. This may take several minutes to complete... 00:00:08.8410140
ExitCode: 404
ExitCode: 404
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to install radare2.flare
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
The install of flarevm.installer.flare was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\flarevm.installer.flare\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - flarevm.installer.flare (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\flarevm.installer.flare\tools\chocolateyinstall.ps1'.
 See log for details.
Chocolatey : Chocolatey reported an unsuccessful exit code of -1. See
C:\Users\Uzr\AppData\Local\Boxstarter\boxstarter.log for details.
At C:\ProgramData\boxstarter\boxstarter.chocolatey\Invoke-ChocolateyBoxstarter.ps1:199 char:5
+     Chocolatey install $bootstrapPackage -source $source -force:$forc ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,chocolatey

+ Boxstarter finished Calling Chocolatey to install flarevm.installer.flare. This may take several minutes to complete... 00:00:33.4421422
True
Boxstarter: Restore Automatic Updates from Windows Update

Errors       : {Chocolatey reported an unsuccessful exit code of -1. See
               C:\Users\Uzr\AppData\Local\Boxstarter\boxstarter.log for details.}
ComputerName : localhost
Completed    : True
FinishTime   : 11/1/2018 2:13:58 PM
StartTime    : 11/1/2018 2:13:24 PM

**Comment by htnhan** [comment]
@anelshaer I think this may be a temporary network issue due to this error: 

ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://radare.mikelloc.com/get/2.6.0/radare2_installer-msvc_64-2.6.0.exe'. 

I just do a quick check and install radare2.flare successfully. Please give it another shot to see if the issue is still there.

Thank you

**Comment by htnhan** [comment]
Are you installing on windows 10? or Windows 7? Another issue could be the long path (C:\Users\<username>\AppData\Local\Temp\<chocolatey_repeated>\) causing Power Shell fail to save the file.

**Comment by anelshaer** [comment]
i'm using windows 10, and thats what i think its because it download the file normally but then stops.

**Comment by nkh8212** [comment]
I'm having the same issue on Windows 10x64.

**Comment by Malworx** [comment]
I went to set up last night and was also having this problem, today i was able to get around it by adding 
**choco config set cacheLocation C:\temp** to the beginning of the install script.

**Comment by mytts** [comment]
I'm having the same issue on Windows 10x64.

**Comment by mytts** [comment]
> I went to set up last night and was also having this problem, today i was able to get around it by adding
> **choco config set cacheLocation C:\temp** to the beginning of the install script.

this worked

**Comment by htnhan** [comment]
@all I just want to confirm the issue, which is similar to another issue we had in the past regarding chocolatey and windows 10.

**Comment by killswitch-GUI** [comment]
I can confirm @Malworx fix works!

**Comment by cbenjamin-christopher** [comment]
Am I adding at the wrong point? Ive tried a couple with the same result

PS C:\> Install-BoxstarterPackage choco config set cacheLocation C:\temp -PackageName https://raw.githubusercontent.com/
fireeye/flare-vm/master/install.ps
Install-BoxstarterPackage : A positional parameter cannot be found that accepts argument 'config'.
At line:1 char:1
+ Install-BoxstarterPackage choco config set cacheLocation C:\temp -Pac ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Install-BoxstarterPackage], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Install-BoxstarterPackage

**Comment by htnhan** [comment]
FLARE VM 2.1 should fix this issue for windows 10.
