### ISSUE TITLE
pestudio CRC mismatch due to update

### ISSUE THREAD

**Issue by moongla-de** [fireeye/flare-vm#146]
Hello,

While installing FLARE VM today I noticed that the download for pestudio has been updated with a new CRC. The install script grabs from the "current" directory, but tries to match with the previous version.

**Comment by htnhan** [comment]
A new version 8.83 is available. Please reinstall PEStudio.

**Comment by YarovoyD** [comment]
Current branch points to Pestudio 8.84, while FLARE compares checksum from 8.83. Please update a checksum for Pestudio 8.84.

**Comment by MalwareMechanic** [comment]
@YarovoyD Thanks for letting us know, checksum for pestudio v8.84 has been updated.
