### ISSUE TITLE
Issue Installing LordPE

### ISSUE THREAD

**Issue by matchstickboy** [fireeye/flare-vm#150]
Hi All,

Sorry to report another issue, but the LordPE install on Win7 64-bit may be broken.  The Bin_LordPE_2010-6-29_3.9_LordPE_1.41_Deluxe_b.zip file seems to be empty when downloaded to a test system on in my lab, causing the Hash evaluation to fail (see attached error).

Hope I am reading this correctly.  please let me know if there is any additional troubleshooting you'd like from my end.

Regards,

Chris
[error.txt](https://github.com/fireeye/flare-vm/files/2548693/error.txt)

**Comment by htnhan** [comment]
@matchstickboy Thank you for reporting the error. However, I can not reproduce it. I try to install lordpe.flare, as well as downloading the zip file manually. They both download successfully.

Does your lab has any AV (on both network and host level) that may detect and quarantine lordPE?

**Comment by matchstickboy** [comment]
Thank you @htnhan.  We do use a web proxy, and it is possible that this is blocking the file download.  Can you provide me with steps on how to manually download the ZIP file for LordPE?  I would like to see if I can reproduce the issue during a manual download.

Regards,

Chris

**Comment by htnhan** [comment]
The zip file can be downloaded here:

http[:]//www.woodmann[.]com/collaborative/tools/images/Bin_LordPE_2010-6-29_3.9_LordPE_1.41_Deluxe_b.zip

Please let us know if it is a web proxy issue, or it's something else entirely.

Thank you

**Comment by matchstickboy** [comment]
Thank you and apologies.  Our Proxy service categorizes www.woodmann.com as a Malicious Web Site.

Please disregard this ticket.

Regards,

Chris
