### ISSUE TITLE
pycrypto install error

### ISSUE THREAD

**Issue by rkropff** [fireeye/flare-vm#152]
Hi, Trying to install the flare vm and am getting an error with pycrypto install and then completely errors out further down. Win10 VM. Thanks!

[Python] Command "c:\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\malware\\AppData\\Local\\ChocoCache\\pip-install-nbozlots\\pycrypto\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\malware\AppData\Local\ChocoCache\pip-record-3dlfqu46\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\malware\AppData\Local\ChocoCache\pip-install-nbozlots\pycrypto\

Chocolatey upgraded 0/0 packages. 0 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
 [Python]     running build_ext
 [Python]     warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
 [Python]     building 'Crypto.Random.OSRNG.winrandom' extension
Chocolatey reported an unsuccessful exit code of 1. See C:\Users\malware\AppData\Local\Boxstarter\boxstarter.log for details.
+ Boxstarter finished Calling Chocolatey to install pycrypto. This may take several minutes to complete... 00:00:10.6347785
+ Boxstarter finished Calling Chocolatey to install pycrypto. This may take several minutes to complete... 00:00:10.6347785

 [Python]     creating build\temp.win-amd64-3.7

ExitCode: 1
 [Python]     creating build\temp.win-amd64-3.7\Release
ExitCode: 1
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to install pycrypto
 [Python]     creating build\temp.win-amd64-3.7\Release\src
 [Python]     C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Isrc/ -Isrc/inc-msvc/ -Ic:\python37\include -Ic:\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcsrc/winrand.c /Fobuild\temp.win-amd64-3.7\Release\src/winrand.obj
 [Python]     winrand.c
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(26): error C2061: syntax error: identifier 'intmax_t'
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(27): error C2061: syntax error: identifier 'rem'
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(27): error C2059: syntax error: ';'
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(28): error C2059: syntax error: '}'
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(30): error C2061: syntax error: identifier 'imaxdiv_t'
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(30): error C2059: syntax error: ';'
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(40): error C2143: syntax error: missing '{' before '__cdecl'
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(41): error C2146: syntax error: missing ')' before identifier '_Number'
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(41): error C2061: syntax error: identifier '_Number'
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(41): error C2059: syntax error: ';'
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(42): error C2059: syntax error: ')'
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(45): error C2143: syntax error: missing '{' before '__cdecl'
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(46): error C2146: syntax error: missing ')' before identifier '_Numerator'
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(46): error C2061: syntax error: identifier '_Numerator'
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(46): error C2059: syntax error: ';'
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(46): error C2059: syntax error: ','
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(48): error C2059: syntax error: ')'
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(50): error C2143: syntax error: missing '{' before '__cdecl'
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(56): error C2143: syntax error: missing '{' before '__cdecl'
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(63): error C2143: syntax error: missing '{' before '__cdecl'
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(69): error C2143: syntax error: missing '{' before '__cdecl'
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(76): error C2143: syntax error: missing '{' before '__cdecl'
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(82): error C2143: syntax error: missing '{' before '__cdecl'
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(89): error C2143: syntax error: missing '{' before '__cdecl'
 [Python]     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(95): error C2143: syntax error: missing '{' before '__cdecl'
 [Python]     error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

**Comment by htnhan** [comment]
@rkropff Thank you for reporting the issue. Is this a fresh installation of windows? Did you already have Python3 installed before installing FLARE VM?

**Comment by htnhan** [comment]
Thank you @rkropff. Issue confirmed.

**Comment by htnhan** [comment]
@rkropff We are supporting both Python2 and Python3. PyCrypto is obsolete and replaced by PyCryptodome for Python3. I have created #156 to replace PyCrypto with PyCryptodome. Thank you for reporting this issue.

**Comment by htnhan** [comment]
Fixed in FLARE VM 2.1
