### ISSUE TITLE
Gvim package not working for x86

### ISSUE THREAD

**Issue by h0pp** [fireeye/flare-vm#154]
Hi,

gvim version included in flare (8.0.604) is not working in Windows 7 32bits as the executables are for 64 bits architecture 
![imagen](https://user-images.githubusercontent.com/31798471/48434953-771a3500-e77b-11e8-8220-ab7f08626af0.png)

![imagen](https://user-images.githubusercontent.com/31798471/48435185-26efa280-e77c-11e8-9a23-4b7c5aebe42a.png)

Current Version - URL: https://sourceforge.net/projects/cream/files/Vim/8.0.604/gvim-8-0-604.exe/download
I have also tested newest version from cream project and they don't work.

Nevertheless, the installer from https://ftp.nluug.nl/pub/vim/pc/gvim81.exe works perfect

Best regards

**Comment by htnhan** [comment]
@h0pp We uses the vim package available from chocolatey. It looks like this package is no longer maintained. We will produce our own package to install vim on both x64 and x86.

Thank you for reporting this issue.

**Comment by htnhan** [comment]
@h0pp Please uninstall vim (using "choco uninstall vim") and install the new "vim.flare" package from the flare feed

**Comment by h0pp** [comment]
Its now working perfect. Thank you so much @htnhan
