### ISSUE TITLE
Win10 VM + Flare Install Script causing tools to be missing

### ISSUE THREAD

**Issue by Jymit** [fireeye/flare-vm#155]
VirtualBox Version 5.2.18 r124319
Win 10 VM
Using the install script method in Powershell, run as admin. The only tools that are installed are:
```
Desktop -> Flare -> Debuggers
-> OllyDbg
-> OllyDbg2
-> scdbg
-> windbgx64
-> windbgx86
-> x32dbg
-> x64dbg

Desktop -> Flare -> Disassemblers
-> idafree70
```
I tested I am able to install `ffdec` and a folder is automatically created under \Desktop\Flare\Flash

This is the third time trying the install this on Win10 with the install script (which was updated 13 days ago) I will share the (choc)install.log shortly.

Is this by design and we must install the tools we need manually?

**Comment by Jymit** [comment]
@htnhan Thanks.
```
2018-11-13 22:35:36,181 1748 [ERROR] - LordPE not installed. The package was not found with the source(s) listed.
2018-11-13 22:43:28,766 5240 [ERROR] - cyberchef not installed. The package was not found with the source(s) listed.
```
I did have a skim through for any sensitive data. The PublicKeyTokens would be publicly available. Please see full install log here: [myChocInstall.log](https://github.com/fireeye/flare-vm/files/2580102/myChocInstall.log)

**Comment by htnhan** [comment]
@Jymit Did you install from the latest release? We recently moved all our packages from <package_name> to <package_name>.flare to avoid name collisions; but you are still using the old names.

**Comment by DavidJBianco** [comment]
I ran into this, too.  It's the same issue as #144.
