### ISSUE TITLE
PDFStreamDumper Checksum Mismatch

### ISSUE THREAD

**Issue by darkdefender1** [fireeye/flare-vm#158]
There is a mismatch of SHA256 hashes of the PDFStremDumper_Setup.exe file that Flare attempts to install.  Have attempted to install this on numerous Windows (7 and 10) virtual machines, with no luck. See errors below:

Download of PDFStreamDumper_Setup.exe (-1 B) completed. 
Download of PDFStreamDumper_Setup.exe (-1 B) completed. 
**Error - hashes do not match. Actual value was '422AAA7685BD29C22DD93875CCA4E7C6847C1DB30C9017E21367612F814B2772'.** 

ERROR: Checksum for 'C:\Users\darkdefender\AppData\Local\Temp\chocolatey\PDFStre amDumper_Setup.exe' did not meet '3297D271DB055194A65F2F46FA073E2CD112C62E5B23CDEDFFE292AC21637599' for checksum type 'sha256'. Consider passing the actual chec ksums through with --checksum --checksum64 once you validate the checksums are a ppropriate. A less secure option is to pass --ignore-checksums if necessary. The upgrade of pdfstreamdumper.flare was NOT successful. Error while running 'C:\ProgramData\chocolatey\lib\PdfStreamDumper.flare\tools\chocolateyinstal1.ps1'. See log for details. 

Chocolatey upgraded 0/1 packages. 1 packages failed. See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log). 

Failures - pdfstreamdumper.flare (exited -1) - Error while running 'C:\ProgramData\choco latey\lib\PdfStreamDumper.flare\tools\chocolateyinstall.ps1'. See log for details. Chocolatey reported an unsuccessful exit code of -1. see C:\Users\darkdefender\A ppData\Local\Boxstarter\boxstarter.log for details. + Boxstarter finished Calling Chocolatey to install pdfstreamdumper.flare. This may take several minutes to complete... 00:00:35.2830231 + Boxstarter finished Calling Chocolatey to install pdfstreamdumper.flare. This may take several minutes to complete... 00:00:35.2830231 
ExitCode: -1 
ExitCode: -1

**Comment by htnhan** [comment]
@darkdefender1 I have tried this multiple time, and unable to reproduce the error. The hash is correct. It is likely that there is a network level filter, or something else blocking the site or the download. Can you check to see if you can manually download the file from the VM?

Thanks,

**Comment by darkdefender1** [comment]
@htnhan apologies, can confirm that this was a networking issue as the firewall was blocking multiple .exe's being installed during the process.

**Comment by htnhan** [comment]
@darkdefender1  No worries. Thank you for using and testing FLARE VM. We appreciate your support.
