### ISSUE TITLE
(429) Too Many Requests due to Rate Limiting from Chocolatey

### ISSUE THREAD

**Issue by Bonfire** [fireeye/flare-vm#167]
Attempting to install the flare-vm suite through Chocolatey now serves you with a "(429) Too Many Requests" error for every single package after the first couple of packages. This is due to Chocolatey's new rate limiting (Package downloads/installations are rate limited at about 20 per minute per IP address). As it stands, I have seen no possible way to install the flare-vm suite with the current setup. Perhaps spacing out the installations would remedy the situation?

Read more about the rate-limiting introduced on November 26, 2018 here: https://chocolatey.org/docs/community-packages-disclaimer#rate-limiting

**Comment by Bonfire** [comment]
Running the `install.ps1` final was enough for me to hit the rate-limit. I had installed the suite yesterday without any issues. After the rate-limiting feature added today, I am unable to install the suite. I understand that after being rate-limited, your IP address is banned for a set amount of hours.

In my case, to reproduce the issue, simply running the installation file was enough for me to be given the "(429) Too Many Requests" error. I suppose depending on the rate limits set by Chocolatey, it is very possible that the fact that I had installed the suite yesterday and tried again to install it today could have set it off but I am unsure. I've been struggling with this for the better part of a day and I am unsure if my installation from yesterday would affect my rate-limiting today.

Looking at the installation though it doesnt seem that my IP address is flat-out rate-limited until I run the installation for a bit (enough to turn on the limiting). I will download and install the first few packages without issue, but after a couple I am hit with the error. I will definitely provide screenshots and logs if I get the chance, but as it stands I believe I am rate-limited so there is not much I can do.

**Comment by Bonfire** [comment]
I will close this for now. I will wait a day and see if the issue is just a result of a very long rate-limiting. If the issue still persists after some time, I will re-open the issue. Thank you for the assistance.

**Comment by paul-michalik** [comment]
Oh no, this happend to me right now too. I was testing my installation scripts with "--whatif" and obviously got banned. How long does it take to be able to download again?

**Comment by theking2** [comment]
This happened to us yesterday when our students were instructed to install chocolatey on their BYOD. It were 26 in total all attempting the installation of chocolatey and after that installing a standard set of packages. We now copied the install.ps1 to our own in house webserver and use that. Unable to test that though.

**Comment by Delta0001** [comment]
Just ran the individual installation command from https://chocolatey.org/install#individual and got immediately rate limited when I tried to install python. Something is seriously wrong with the rate limiting.
