### ISSUE TITLE
Failure run after reboot for completing installation

### ISSUE THREAD

**Issue by placebocoder** [fireeye/flare-vm#168]
Hi all!

I installed that downloaded and executed it as described your blog. But I got errors in Korean below.(That means cannot connected)

![2018-11-27 16 31 06](https://user-images.githubusercontent.com/39292357/49065689-19e5af80-f262-11e8-975c-c0f3848d505c.jpg)

So that I tried to connect on browser, I got a message below

<img width="979" alt="screenshot of safari 27-11-2018 4-28-16 pm" src="https://user-images.githubusercontent.com/39292357/49065661-05091c00-f262-11e8-92a5-10791604a26c.png">

How can I fix it? Plz help me.

**Comment by htnhan** [comment]
Is it possible there is a network issue at the install time? Can you check again? Not sure if this is FLARE VM issue, or chocolatey issue.
