### ISSUE TITLE
Error while Updating and Installing

### ISSUE THREAD

**Issue by min0rchanges** [fireeye/flare-vm#169]
While trying todo a fresh install or updating via cup all on different windows (8 and 10) the following errors accure by different packages:
ERROR: Cannot bind argument to parameter 'Path' because it is null.
The install of PACKAGENAME.flare was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\wireshark.flare\tools\chocolateyInstall.ps1'.
 See log for details.

A few weeks ago, everything was working flawlessly.

Any ideas?

**Comment by MalwareMechanic** [comment]
@min0rchanges we recently updated flare-vm to 2.0 which had some breaking changes. The `$path` variable in `wireshark.flare` now depends on the environment variable `FLARE_START`. Can you see if this environment variable is set for you? I would also recommend a fresh install if you haven't already installed the newer 2.0 version.

**Comment by min0rchanges** [comment]
Hi,
installed the new version like you recommended and the bug is gone. Thanks for the fast reply.
The information with the upgrade to the new flare vm and how to do it, should be placed somewhere easier to see, because on the mainsite the instructions are misleading.

Anyway thanks for the fast help.
Regards
Tim

**Comment by MalwareMechanic** [comment]
Thanks, I'll update the readme with more information regarding v2.0.
