### ISSUE TITLE
VB Decompiler new version - installation failed

### ISSUE THREAD

**Issue by 2xyo** [fireeye/flare-vm#18]
VB Decompiler Lite has been [updated](https://www.vb-decompiler.org/news.htm) in August and installation fails because the new checksum `A82CD878F18E391F05416C7DC2D3F9F0B4E255EE9867ACAB89843E66BBB84256` do not meet the package checksum  `b186813f15cac8f69dd65554cd34426c38eefdd48533c2b299a42456f2df91fc`.

**Comment by iphelix** [comment]
Updated the package. Should be working now.
