### ISSUE TITLE
Some software still not installing due to checksum mismatch

### ISSUE THREAD

**Issue by cscgoat** [fireeye/flare-vm#184]
Some software do not install even after commit 451eec2 due to checksum mismatch, including Wireshack, Procmon.

**Comment by htnhan** [comment]
@cscgoat Thank you for reporting the issue. 

procmon is part of sysinternals.flare. Does sysinternals.flare package install/upgrade successfully? Do you have the exact output with errors for procmon?

I'll check Wireshark as well.

Nhan T. Huynh

**Comment by htnhan** [comment]
@cscgoat  Can you confirm again what errors do you have with wireshark? I just check, and can install wireshark.flare package normally. I also do not see any issues installing sysinternals.flare package

**Comment by cscgoat** [comment]
Hi @htnhan,

I can confirm that this issue do not occur upon installation on a fresh Windows 7 x64 VM.

I initially encountered the issue when I installed using previous commit. I updated to latest commit and attempted installation again on same VM but issue persisted, although everything was fine after adding --ignore-checksum flag.

Thank you.
