### ISSUE TITLE
Some packages failed to install

### ISSUE THREAD

**Issue by m4now4r** [fireeye/flare-vm#185]
Dir htnhan,

Thanks for maintaining the greate VM for RE/Malware Analysis. 
Here is the boxstarter log file when i try to install

**_dnSpy log:_**
Url request/response failed - file name will be 'dnspyInstall.zip':  Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
[2019-01-12T23:27:55.1352909+07:00:::PID 384] Attempt to get headers for https://github.com/0xd4d/dnSpy/releases/download/v5.0.11/dnSpy.zip failed.
Attempt to get headers for https://github.com/0xd4d/dnSpy/releases/download/v5.0.11/dnSpy.zip failed.
Chocolatey upgraded 0/1 packages. 1 packages failed.
[2019-01-12T23:28:00.2142743+07:00:::PID 384] Failed to install dnspy.flare
Failed to install dnspy.flare

**_metasploit-framework_:**

[2019-01-12T23:39:31.2617359+07:00:::PID 384] Attempt to get headers for https://windows.metasploit.com/metasploit-framework-4.17.33%2B20181221154748-1rapid7-1-x86.msi failed.
Attempt to get headers for https://windows.metasploit.com/metasploit-framework-4.17.33%2B20181221154748-1rapid7-1-x86.msi failed.
Chocolatey upgraded 0/1 packages. 1 packages failed.
[2019-01-12T23:39:35.6292412+07:00:::PID 384] Failed to install metasploit.flare
Failed to install metasploit.flare

**_pestudio_**
[2019-01-12T23:44:11.8017352+07:00:::PID 384] Failed to install pestudio.flare
Failed to install pestudio.flare

[2019-01-12T23:48:49.9811581+07:00:::PID 384] Failed to install lessmsi.fireeye
Failed to install lessmsi.fireeye

[2019-01-13T00:16:57.4672860+07:00:::PID 6256] Failed to install MAP.flare
Failed to install MAP.flare

**Comment by htnhan** [comment]
@m4now4r Hi anh. Please give it another try. We just upgraded the following packages to the latest versions:

dnSpy.flare
metasploit.flare
pestudio.flare

lessmsi.fireeye and MAP.flare seems to install properly on my end.

**Comment by m4now4r** [comment]
Hi htnhan,

Thanks so much for quickly response!
dnSpy.flare (v6.0); metasploit.flare ; pestudio.flare (v8.88) and lessmsi.fireeye (v1.6.3) packages are installed properly.

But MAP.flare still error to me ( I have tried two time):
![image](https://user-images.githubusercontent.com/27551832/51086608-0c857580-177b-11e9-9c9c-9eb84f015f4f.png)

Regards,
m4n0w4r

**Comment by m4now4r** [comment]
Hi @htnhan,

Today, i retry the script and everything work fine!! MAP.flare is installed properly:

![image](https://user-images.githubusercontent.com/27551832/51190996-0972bc80-1916-11e9-9dd9-96d56452822f.png)

@htnhan: Just inform you some packages has released new version:
PE-bear – version 0.3.9: https://hshrzd.wordpress.com/2019/01/13/pe-bear-version-0-3-9-available/
Exeinfo 0.0.5.2 - ( 1021 / 69 - x64   signatures ) : http://exeinfo.xn.pl/
x64dbg2019-01-11: https://github.com/x64dbg/x64dbg/releases

**Comment by zygmuntg** [comment]
Same problem again with vb_decompiler_lite and metasploit.flare. 
The problem with Metasploit is that the version 5.0.9.20190224* has been removed from windows.metasploit.com. May be it would be better to use metasploitframework-latest.msi in installation script?

**Comment by htnhan** [comment]
@m4now4r I have created #205 and #204 to track PE Bear and Exeinfo upgrade. x64dbg has been upgraded to a new snapshot.

@zygmuntg Please refer to #203 for issues related to metasploit installer. vbdecompiler issue has been fixed.
