### ISSUE TITLE
three problems

### ISSUE THREAD

**Issue by baosj0** [fireeye/flare-vm#191]
1. http://windows.metasploit.com/metasploit-framework-5.0.3%2B20190128203328-1rapid7-1-x64.msi  missing
2. https://ci.appveyor.com/api/buildjobs/uju7e5t18hfxua9m/artifacts/release.zip missing
3. `Download of pestudio.zip (917.76 KB) completed.
Download of pestudio.zip (917.76 KB) completed.
Error - hashes do not match. Actual value was '91C511798616C75AC919632BDCEF4A2FF49A48189E7D36D10D015CC2856E8CB2'.
ERROR: Checksum for 'C:\Users\Mike\chocolatey\pestudio.flare\8.88\pestudio.zip' did not meet '2E429AA05EA51CD27FE7F51092
AA19200B10EA81AEF957D5D3ABEEE77CB579F0' for checksum type 'sha256'. Consider passing the actual checksums through with -
-checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksu
ms if necessary.
The upgrade of pestudio.flare was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\pestudio.flare\tools\chocolateyinstall.ps1'.
 See log for details.`

**Comment by htnhan** [comment]
Fixed. Please let us know if you still experience issues with these packages.

For future references, please create an issue for each package so we can easily track and close the issues properly.
