### ISSUE TITLE
oledump.py is missing

### ISSUE THREAD

**Issue by brkalbyrk** [fireeye/flare-vm#195]
MS Office. .doc, .xls, .ppt, … are OLE files (docx, xlsx, … is the new file format: XML inside ZIP).
This program is need to oledump.py because its too good analyzer for office files. I think flare-vm is need this tool. 
https://blog.didierstevens.com/programs/oledump-py/

**Comment by MalwareMechanic** [comment]
@brkalbyrk I added this tools under the `Office` tool category directory. I also created shortcuts for all the tools provided by [`oletools`](https://github.com/decalage2/oletools/wiki) in the `Office` directory as well.
