### ISSUE TITLE
add innounp

### ISSUE THREAD

**Issue by williballenthin** [fireeye/flare-vm#198]
I'd like to suggest that innounp, the Inno Setup Unpacker, be added to flare-vm. Its available here: http://innounp.sourceforge.net/

**Comment by williballenthin** [comment]
also: http://constexpr.org/innoextract/

**Comment by MalwareMechanic** [comment]
Both are added! I also added [UniExtract2](https://github.com/Bioruebe/UniExtract2) which can extract many different file types.
