### ISSUE TITLE
wallpaper/theme not applied on Windows 10 LTSB edition

### ISSUE THREAD

**Issue by wh1t3-n01s3** [fireeye/flare-vm#2]
Great job putting together a Windows based Malware/Forensics platform.

Needs a custom theme though. Or at minimum a branded desktop background like the one on the screenshots here: https://www.fireeye.com/blog/threat-research/2017/07/flare-vm-the-windows-malware.html

If it's already included, it isn't present when installing to a Windows 10 LTSB edition.

**Comment by Chiggins** [comment]
Well the desktop background does get applied, as well as the smaller [taskbar](https://github.com/fireeye/flare-vm/blob/master/flarevm_malware.ps1#L87).

**Comment by wh1t3-n01s3** [comment]
What is the name of the background and where is it stored?  It didn't apply on my install.

**Comment by Neodyn** [comment]
Is it possible to e.q deactivate the UAC, Windows defender.  Imho it would be great to create a weak / insecure windows 7.

**Comment by andyrat33** [comment]
Would it be possible to add Process Hacker?
hxxp://processhacker.sourceforge.net

**Comment by williballenthin** [comment]
@andyrat33 your enhancement suggestion is tracked at #7

**Comment by williballenthin** [comment]
@Neodyn your enhancement suggestion is tracked at #8

**Comment by williballenthin** [comment]
i've migrated independent feature suggestions to their own issues so we can have separate discussions about them. thanks @Neodyn @andyrat33 for the ideas!

**Comment by htnhan** [comment]
Closing this old issue due to inactivity.
