### ISSUE TITLE
floss WARNING missing vtrace platforms

### ISSUE THREAD

**Issue by RonnieSalomonsen** [fireeye/flare-vm#20]
When running floss you get following warning:

`WARNING:vtrace.platforms.win32:LoadLibrary c:\program files\python27\lib\site-packages\vtrace\platforms\windll\amd64\sym
srv.dll: [Error 126] The specified module could not be found
WARNING:vtrace.platforms.win32:LoadLibrary c:\program files\python27\lib\site-packages\vtrace\platforms\windll\amd64\dbg
help.dll: [Error 126] The specified module could not be found`

Fixed by downloading the missing files frrom vivisect:
vivisect/vtrace/platforms/windll/

So looks like something is not installed correctly with the flarevm powershell script

**Comment by williballenthin** [comment]
this is a (minor) issue with floss tracked here: https://github.com/fireeye/flare-floss/issues/234

we don't use the dbghelp subsystem in vivisect and therefore don't package those binary dependencies with floss (licensing, file size, etc.).  we need to update the logging config to avoid reporting this non-fatal error.

i recommend that we continue further discussion on the floss issue, as this is not flare-vm specific.

**Comment by williballenthin** [comment]
should be closed in 3980f9f0a76e87b91f1f4211057c7fac0a045430
