### ISSUE TITLE
Add Winace

### ISSUE THREAD

**Issue by Maijin** [fireeye/flare-vm#200]
Add Winace to deal with ACE files

**Comment by MalwareMechanic** [comment]
@Maijin 7-zip can extract ACE files (right-click and use 7-zip). However, I've also added [UniExtract2](https://github.com/Bioruebe/UniExtract2) which can also extract ACE files. Hopefully this meets your needs.

**Comment by Maijin** [comment]
7z not always works with ACE. But I will come with an example next time I meet with one
