### ISSUE TITLE
wireshark can't start missing api-ms-win-crt-runtime-I1-1-0.dll

### ISSUE THREAD

**Issue by andyrat33** [fireeye/flare-vm#21]
wireshark can't start missing api-ms-win-crt-runtime-I1-1-0.dll

**Comment by iphelix** [comment]
confirmed working on the latest release. Please reopen if you are still seeing this issue.

**Comment by andyrat33** [comment]
wireshark can't start missing api-ms-win-crt-runtime-I1-1-0.dll this is still an issue on a 64bit Windows 7 install.
