### ISSUE TITLE
Feature Request: Implement mkYara

### ISSUE THREAD

**Issue by agithubuserlol** [fireeye/flare-vm#215]
https://pypi.org/project/mkYARA/ is a pretty excellent tool for generating Yara rules based on arbitrary binary data in executables. I think it would make a valuable addition to the FLARE-VM arsenal.

Would it be possible to consider it for inclusion in a future release?

**Comment by MalwareMechanic** [comment]
@agithubuserlol We've added this to our Python libraries. You can update them with:
- `choco upgrade libraries.python2.fireeye`
- `choco upgrade libraries.python3.fireeye`
