### ISSUE TITLE
PEStudio install fails due to wrong version checksum

### ISSUE THREAD

**Issue by jamesbercegay** [fireeye/flare-vm#218]
The current FlareVM install process will error due to a checksum mismatch when downloading PEStudio. This is because a new version of PEStudio were released a couple of weeks ago. (8.93)

From what I can tell FlareVM is linking to:

https://winitor.com/tools/pestudio/current/pestudio.zip 

Which is a dynamically generated archive of the latest version. Yet, FlareVM checks it against a checksum for a specific version? Why not link to the specific version you are comparing against? (even if you have to host it) I ask because it seems this PEStudio checksum mismatch is a reoccurring issue for FlareVM.

Attached is a screenshot if that helps.
![screen](https://user-images.githubusercontent.com/2095787/57607352-7ac32480-7530-11e9-9963-7b72159c5360.png)

**Comment by MalwareMechanic** [comment]
@jamesbercegay Thanks for reporting this! The pestudio package has been updated to version 8.93. You can reinstall it using an admin PowerShell prompt via `cinst pestudio.flare`
