### ISSUE TITLE
Add additional java decompilers

### ISSUE THREAD

**Issue by htnhan** [fireeye/flare-vm#221]
https://www.benf.org/other/cfr/
and 
https://github.com/Storyyeller/Krakatau

**Comment by MalwareMechanic** [comment]
I believe bytecode-viewer already has Krakatau built in. It's listed as a feature and is in the source directory: https://github.com/Konloch/bytecode-viewer/tree/master/src

**Comment by htnhan** [comment]
bytecode-viewer already include Krakatau. It also "utilizes FernFlower, Procyon, CFR, and JD for decompilation" according to README.
