### ISSUE TITLE
Add Java-Deobfuscator

### ISSUE THREAD

**Issue by jdmaster85** [fireeye/flare-vm#222]
Recently I have analyzed lots of java RAT (due to cross-platform capability) with multi layer obfuscations and I found out Java-Deobfuscator do the job greater than other tools. They come with GUI too in case user having issue to setup the config file.

Java-Deobfuscator
https://github.com/java-deobfuscator/deobfuscator

GUI
https://github.com/java-deobfuscator/deobfuscator-gui

**Comment by opticoax747** [comment]
Inside PDFStreamDumper there is some JavaCode Analysis...also maybe jsunpack or js-detox

**Comment by MalwareMechanic** [comment]
@jdmaster85 We've added a package for Java-Deobfuscator-Gui. You can install via `choco install java-deobfuscator-gui.fireeye`
