### ISSUE TITLE
Checksum Mismatch IDR

### ISSUE THREAD

**Issue by samfree91** [fireeye/flare-vm#232]
On running install.ps1 on windows10 V 1809

`
C:\ProgramData\chocolatey\lib\idr.small.flare\tools
Downloading idr.small.flare
  from 'https://www.dropbox.com/sh/9ran313nidqtagb/AADl_m_9GVYSiXUviZtDQWQHa?dl=1'
Downloading idr.small.flare
  from 'https://www.dropbox.com/sh/9ran313nidqtagb/AADl_m_9GVYSiXUviZtDQWQHa?dl=1'

Download of idr.small.flareInstall.zip (-1 B) completed.
Download of idr.small.flareInstall.zip (-1 B) completed.
Error - hashes do not match. Actual value was '2FE2F16E129A979CDDFE252259E04CC4B689487DD4F33EFFC805E45EC11B15BD'.
ERROR: Checksum for 'C:\Users\user\AppData\Local\ChocoCache\idr.small.flare\2017.01.04\idr.small.flareInstall.zip' did not meet '6C015174E630191926266FB5624EE46442F55C195200286D0FF5B11399DE50D8' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The upgrade of idr.small.flare was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\idr.small.flare\tools\chocolateyinstall.ps1'.

`

**Comment by gshmu** [comment]
sha256 did't match, but retry after every reboot.
```
Download of idr.small.flareInstall.zip (-1 B) completed.
Error - hashes do not match. Actual value was '2FE2F16E129A979CDDFE252259E04CC4B689487DD4F33EFFC805E45EC11B15BD'.
ERROR: Checksum for 'C:\Users\IEUser\AppData\Local\Temp\idr.small.flare\2017.01.04.2\idr.small.flareInstall.zip' did not meet '6C015174E630191926266FB5624EE46442F55C195200286D0FF5B11399DE50D8' for checksum type 'sha256'.
```

**Comment by samfree91** [comment]
I've tried a reboot, and different versions of windows 10 VM's with no long, if keeps failing the sha256 checksum.

**Comment by miketweaver** [comment]
I have this same issue as well. It appears to be a problem with this package for everyone.

**Comment by samfree91** [comment]
Hi there,

Just tried to run the flare install / update script again with no luck, i’m still getting a checksum mismatch for idr.small.flare

________________________________

**Comment by samfree91** [comment]
All good, it worked thus time thanks for that
