### ISSUE TITLE
Error running Process Explorer

### ISSUE THREAD

**Issue by bloomer1016** [fireeye/flare-vm#246]
Hello all,

Installed Flare via the PoSH script onto my Windows 7 Pro x64 SP1 VM (Microsoft Windows [Version 6.1.7601]). Everything seems to work alright except Process Explorer as it keeps crashing. Attached are the errors that are thrown and the crash details listed below as well. 

####################################
Problem signature:
  Problem Event Name:	BEX64
  Application Name:	procexp64.exe
  Application Version:	16.30.0.0
  Application Timestamp:	5d70cac3
  Fault Module Name:	StackHash_1dc2
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Offset:	0000000000000000
  Exception Code:	c0000005
  Exception Data:	0000000000000008
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	1dc2
  Additional Information 2:	1dc22fb1de37d348f27e54dbb5278e7d
  Additional Information 3:	cbc5
  Additional Information 4:	cbc5ec6970b2af35927ad67117ca57e2

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
####################################

I also have listed below the 'report.wer' report from this crashing in case it helps.

####################################
Version=1
EventType=BEX64
EventTime=132167479980877087
ReportType=2
Consent=1
ReportIdentifier=acb9afd4-f992-11e9-9876-0800275654f2
IntegratorReportIdentifier=acb9afd3-f992-11e9-9876-0800275654f2
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=procexp64.exe
Sig[1].Name=Application Version
Sig[1].Value=16.30.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=5d70cac3
Sig[3].Name=Fault Module Name
Sig[3].Value=StackHash_1dc2
Sig[4].Name=Fault Module Version
Sig[4].Value=0.0.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=00000000
Sig[6].Name=Exception Offset
Sig[6].Value=0000000000000000
Sig[7].Name=Exception Code
Sig[7].Value=c0000005
Sig[8].Name=Exception Data
Sig[8].Value=0000000000000008
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=6.1.7601.2.1.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=1dc2
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=1dc22fb1de37d348f27e54dbb5278e7d
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=cbc5
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=cbc5ec6970b2af35927ad67117ca57e2
UI[2]=C:\ProgramData\chocolatey\lib\sysinternals\tools\procexp64.exe
UI[3]=Sysinternals Process Explorer has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\ProgramData\chocolatey\lib\sysinternals\tools\procexp64.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\system32\kernel32.dll
LoadedModule[3]=C:\Windows\system32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\system32\SHLWAPI.dll
LoadedModule[5]=C:\Windows\system32\GDI32.dll
LoadedModule[6]=C:\Windows\system32\USER32.dll
LoadedModule[7]=C:\Windows\system32\LPK.dll
LoadedModule[8]=C:\Windows\system32\USP10.dll
LoadedModule[9]=C:\Windows\system32\msvcrt.dll
LoadedModule[10]=C:\Windows\system32\IPHLPAPI.DLL
LoadedModule[11]=C:\Windows\system32\NSI.dll
LoadedModule[12]=C:\Windows\system32\WINNSI.DLL
LoadedModule[13]=C:\Windows\system32\RPCRT4.dll
LoadedModule[14]=C:\Windows\system32\WS2_32.dll
LoadedModule[15]=C:\Windows\system32\MPR.dll
LoadedModule[16]=C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.17514_none_fa396087175ac9ac\COMCTL32.dll
LoadedModule[17]=C:\Windows\system32\VERSION.dll
LoadedModule[18]=C:\Windows\system32\credui.dll
LoadedModule[19]=C:\Windows\system32\SETUPAPI.dll
LoadedModule[20]=C:\Windows\system32\CFGMGR32.dll
LoadedModule[21]=C:\Windows\system32\ADVAPI32.dll
LoadedModule[22]=C:\Windows\SYSTEM32\sechost.dll
LoadedModule[23]=C:\Windows\system32\OLEAUT32.dll
LoadedModule[24]=C:\Windows\system32\ole32.dll
LoadedModule[25]=C:\Windows\system32\DEVOBJ.dll
LoadedModule[26]=C:\Windows\system32\CRYPT32.dll
LoadedModule[27]=C:\Windows\system32\MSASN1.dll
LoadedModule[28]=C:\Windows\system32\ACLUI.dll
LoadedModule[29]=C:\Windows\system32\SHELL32.dll
LoadedModule[30]=C:\Windows\system32\NTDSAPI.dll
LoadedModule[31]=C:\Windows\system32\POWRPROF.dll
LoadedModule[32]=C:\Windows\system32\WTSAPI32.dll
LoadedModule[33]=C:\Windows\system32\UxTheme.dll
LoadedModule[34]=C:\Windows\system32\COMDLG32.dll
LoadedModule[35]=C:\Windows\system32\WINHTTP.dll
LoadedModule[36]=C:\Windows\system32\webio.dll
LoadedModule[37]=C:\Windows\system32\PSAPI.DLL
LoadedModule[38]=C:\Windows\system32\IMM32.DLL
LoadedModule[39]=C:\Windows\system32\MSCTF.dll
LoadedModule[40]=C:\Windows\system32\api-ms-win-core-synch-l1-2-0.DLL
LoadedModule[41]=C:\Windows\system32\ntmarta.dll
LoadedModule[42]=C:\Windows\system32\WLDAP32.dll
LoadedModule[43]=C:\Windows\system32\dwmapi.dll
LoadedModule[44]=C:\Windows\system32\CRYPTBASE.dll
LoadedModule[45]=C:\Windows\system32\CLBCatQ.DLL
LoadedModule[46]=C:\Windows\system32\dbghelp.dll
LoadedModule[47]=C:\Windows\system32\mscoree.dll
LoadedModule[48]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll
LoadedModule[49]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\CorperfmonExt.dll
LoadedModule[50]=C:\Windows\system32\VCRUNTIME140_CLR0400.dll
LoadedModule[51]=C:\Windows\system32\ucrtbase_clr0400.dll
LoadedModule[52]=C:\Windows\system32\netfxperf.dll
LoadedModule[53]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\perfcounter.dll
LoadedModule[54]=C:\Windows\system32\pdh.dll
LoadedModule[55]=C:\Windows\system32\WindowsCodecs.dll
LoadedModule[56]=C:\Windows\system32\apphelp.dll
LoadedModule[57]=C:\Windows\system32\EhStorShell.dll
LoadedModule[58]=C:\Windows\system32\PROPSYS.dll
LoadedModule[59]=C:\PROGRA~1\MICROS~1\Office14\GROOVEEX.DLL
LoadedModule[60]=C:\Windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_08e61857a83bc251\MSVCR90.dll
LoadedModule[61]=C:\Windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_08e61857a83bc251\MSVCP90.dll
LoadedModule[62]=C:\Windows\WinSxS\amd64_microsoft.vc90.atl_1fc8b3b9a1e18e3b_9.0.30729.6161_none_0a1fd3a3a768b895\ATL90.DLL
LoadedModule[63]=C:\PROGRA~1\COMMON~1\MICROS~1\OFFICE14\Cultures\office.odf
LoadedModule[64]=C:\PROGRA~1\MICROS~1\Office14\1033\GrooveIntlResource.dll
LoadedModule[65]=C:\Windows\System32\cscui.dll
LoadedModule[66]=C:\Windows\System32\CSCDLL.dll
LoadedModule[67]=C:\Windows\system32\CSCAPI.dll
LoadedModule[68]=C:\Windows\system32\ntshrui.dll
LoadedModule[69]=C:\Windows\system32\srvcli.dll
LoadedModule[70]=C:\Windows\system32\slc.dll
LoadedModule[71]=C:\Windows\system32\taskschd.dll
LoadedModule[72]=C:\Windows\system32\SspiCli.dll
LoadedModule[73]=C:\Windows\system32\WINSTA.dll
FriendlyEventName=Stopped working
ConsentKey=BEX64
AppName=Sysinternals Process Explorer
AppPath=C:\ProgramData\chocolatey\lib\sysinternals\tools\procexp64.exe
####################################

Downloading the file from SysInternals and running it gives me the same error as well. 

Attached are some images from the crash and the log from the install. Please let me know if I am missing something. Thanks!

[chocolatey_install.log](https://github.com/fireeye/flare-vm/files/3779344/chocolatey_install.log)
![crash](https://user-images.githubusercontent.com/12056770/67690983-d44ace80-f96b-11e9-82b6-c08fd36f09a3.png)
![3rd err](https://user-images.githubusercontent.com/12056770/67690984-d44ace80-f96b-11e9-9be2-6f23db0d60fc.png)
![2nd err](https://user-images.githubusercontent.com/12056770/67690986-d44ace80-f96b-11e9-9e57-6aa600a5ecaa.png)
![1st err](https://user-images.githubusercontent.com/12056770/67690987-d4e36500-f96b-11e9-88ac-4a8f02c781a6.png)

**Comment by htnhan** [comment]
@bloomer1016 Do you mind doing another quick check for us by downloading and running process explorer from the following URL: `https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer`. I believe the latest version of process explorer may not work properly on windows 7.

**Comment by bloomer1016** [comment]
Hello htnhan,

From the looks of it you are correct. The latest version doesn't seem to work on Windows 7. Since this is not a Flare issue I am closing this one out. Thanks for the assistance.

**Comment by meir444** [comment]
Install KB3033929
https://www.microsoft.com/en-us/download/confirmation.aspx?id=46148
