### ISSUE TITLE
Installation Error - myget.org is down

### ISSUE THREAD

**Issue by DJ-Shields** [fireeye/flare-vm#250]
Error when performing default installation..

```
[NuGet] An error occurred while loading packages from 'https://www.myget.org/F/fireeye/api/v2': The remote server returned an error: (503) Server Unavailable.
flarevm.installer.flare not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "C:\ProgramData\boxstarter\BuildPackages;https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2"
```

Confirmation this is bigger than me, and has been down for >5 days as I type this.

https://www.isitdownrightnow.com/myget.org.html

**Comment by divinehand** [comment]
Confirmed for me too.  I'm getting same issue.  getting 503 errors on myget.org  Choco sources below:

PS C:\~~~\flare-vm-master\flare-vm-master> choco sources
Chocolatey v0.10.15
chocolatey - https://chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.
flare - https://www.myget.org/F/flare/api/v2 | Priority 1|Bypass Proxy - False|Self-Service - False|Admin Only - False.
fireeye - https://www.myget.org/F/fireeye/api/v2 | Priority 1|Bypass Proxy - False|Self-Service - False|Admin Only - Fal
se.

**Comment by divinehand** [comment]
Can I switch the chocolatey.org source to Priority **1** and have my installation work?

**Comment by MalwareMechanic** [comment]
Today I did a build and it completed fine. Myget.org also seems back up. Please let us know if this is still a problem.

**Comment by divinehand** [comment]
Any word or update on why the site is still down?  I'd really love to get this installed someday soon, thanks all!

**Comment by divinehand** [comment]
Nevermind on my last, I hadn't refreshed the page, sorry!  I deleted my last comment.  I'll try again!

**Comment by divinehand** [comment]
Do we know what happened?  Were they having an incident?

**Comment by DJ-Shields** [comment]
I haven't had time to confirm from within the Install script, but looks good just hitting the API so I imagine this is resolved. 

@divinehand I had a hunt for some info on why it was down initially, and found nothing. Because it was down for so long I had my doubts it would come back.

**Comment by kodaman2** [comment]
Seems is down again, the day I want to install flare vm. Bad luck I guess.

![image](https://user-images.githubusercontent.com/10265682/85957501-74218780-b953-11ea-9c5f-6253a8b08caa.png)
