### ISSUE TITLE
Error when installing dnspy

### ISSUE THREAD

**Issue by ant1** [fireeye/flare-vm#251]
There is a 404 error when installing dnspy,  it seems they removed the old version when they released version 6.1.0

**Comment by mxm0z** [comment]
Exactly. I'm getting the same error. 

$ cinst -y dnspy.flare
> Attempt to get headers for https://github.com/0xd4d/dnSpy/releases/download/v6.0.5/dnSpy-net472.zip failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/0xd4d/dnSpy/releases/download/v6.0.5/dnSpy-net472.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading dnspy
  from 'https://github.com/0xd4d/dnSpy/releases/download/v6.0.5/dnSpy-net472.zip'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/0xd4d/dnSpy/releases/download/v6.0.5/dnSpy-net472.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
The install of dnspy.flare was NOT successful.

The URL should be updated to https://github.com/0xd4d/dnSpy/releases/download/v6.1.0/dnSpy-net472.zip

The previous version isn't available anymore

**Comment by mxm0z** [comment]
@ant1 installing the package directly using `choco install dnspy` instead of `cinst` as specified on https://github.com/fireeye/flare-vm/blob/2031bb96dcee740d06d72fb118f91f936f4dd5f5/packages.csv worked for me

**Comment by htnhan** [comment]
Folks, I've updated dnSpy to v6.1.0.

**Comment by edevil** [comment]
The dnspy version is outdated again. We're now at `6.1.1`. Is there a public repository to which we can submit a PR to update the version the dnspy.flare package tries to install?
