### ISSUE TITLE
Persistent installation error: "Chocalatey reported an unsuccessful error code of 1"

### ISSUE THREAD

**Issue by amirootyet** [fireeye/flare-vm#254]
I have been installing FLARE VM on quite a few of my devices in the past couple of months. The installation goes smoothly half the times and doesn't the other half (even on the same machine).

What I did:
I followed the exact installation steps detailed on the README. 
 -- download and unzip flare on the Desktop
 --start Powershell (admin)
 --set execution policy using the provided command.
 --.\install.ps1

I also use Defender Control 1.5 to turn off defender otherwise I start getting warnings by defender during the install process (even if I don't do this step, installation still fails.)

Installation fails consistently as seen in this image:

![Screen Shot 2019-11-21 at 11 37 00 PM](https://user-images.githubusercontent.com/46239148/69484611-4b587300-0e03-11ea-8dc2-9d65becb8381.png)

System:
--Vmware Fusion 11
--Windows 10 Home, 1909, OS build 18363.418

Installation is randomly successful after I've tried a fresh install a few times by reverting back to snapshot and restarting.

**Comment by htnhan** [comment]
@amirootyet  We have a few open tickets for packages being updated so the hashes do not match. Those packages will fail, causing FLARE VM to report some installation error. However, I expect the rest of the Vm still work properly. 

If you believe something else cause the error, please also share `boxstarter.log` and `summary.log` under `%programdata%\chocolatey\logs` to help us investigate this better.

Thank you,
