### ISSUE TITLE
What is the total size of this installation?  My VM is at 40GB?

### ISSUE THREAD

**Issue by opticoax747** [fireeye/flare-vm#259]
What is the total size of this install, I am trying to add some other items but its showing the VM is now 40GB?

What is taking up all the space?

**Comment by htnhan** [comment]
@opticoax747 If you already have a VM, it may be best to check your own VM to see which one takes up all the space. On a clean installation for windows 7 64bit, the entire install should be almost 30Gb. If you are using windows 10 with docker and WSL, the size is significantly larger.

**Comment by turbosmurfen** [comment]
I didn't find requirements in the readme about the size.  I had around 30Gb free space till I noticed that the partion  decreased fast. So I was needed to resize the VM space. So please add requirements.
