### ISSUE TITLE
install.ps1 fails on some versions on Windows 10

### ISSUE THREAD

**Issue by SumithManiath** [fireeye/flare-vm#273]
Powershell uses TLS 1.0 for connections and install.ps1 is failing on Windows 10 (10.0.10240)
Error message:
```
Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: Could not create SSL/TLS secure channel."
```

Making the changes to following lines seems to fix the issues:
`$AllProtocols = [System.Net.SecurityProtocolType]'Ssl3,Tls,Tls11,Tls12'`
to 
`$AllProtocols = [System.Net.SecurityProtocolType]'Tls12'`

and 
$AllProtocols = [System.Net.SecurityProtocolType]'Ssl3,Tls'
to
`$AllProtocols = [System.Net.SecurityProtocolType]'Tls12'`

Im not sure whether this change will break the script on other platforms.

**Comment by bulbafett** [comment]
Working with Windows 10 MSEdge free VM fully updated this edit fixed download issues I had

**Comment by firas55** [comment]
> Powershell uses TLS 1.0 for connections and install.ps1 is failing on Windows 10 (10.0.10240)
> Error message:
> 
> ```
> Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: Could not create SSL/TLS secure channel."
> ```
> 
> Making the changes to following lines seems to fix the issues:
> `$AllProtocols = [System.Net.SecurityProtocolType]'Ssl3,Tls,Tls11,Tls12'`
> to
> `$AllProtocols = [System.Net.SecurityProtocolType]'Tls12'`
> 
> and
> $AllProtocols = [System.Net.SecurityProtocolType]'Ssl3,Tls'
> to
> `$AllProtocols = [System.Net.SecurityProtocolType]'Tls12'`
> 
> Im not sure whether this change will break the script on other platforms.

Worked like a charm for my Windows 7 Enterprise w/ latest updates

**Comment by MalwareMechanic** [comment]
We've pushed a new update, please let me know if this is still a recurring issue

**Comment by tvarath** [comment]
Thanks for the new update!!

I could installation was successful on fresh Windows10
