### ISSUE TITLE
Suggestion: Include malwarejail in FLARE-VM

### ISSUE THREAD

**Issue by agithubuserlol** [fireeye/flare-vm#276]
REF:
https://github.com/HynekPetrak/malware-jail

This service is incredibly valuable for analyzing JavaScript, especially for samples that leverage Windows JScript engine alongside the Windows Script Host. I have not found another tool that handles WScript implementation like this one does.

I use it regularly for annoying samples, and comb through the JSON output by the sandbox in a VM for things I would otherwise have to use a browser debugger to enumerate manually.

I should also note that the author of this service has been responsive via email for (publicly available) samples that the tool does not already handle correctly.

**Comment by htnhan** [comment]
Added `malware-jail.fireeye` package
