### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by DaronBaron** [fireeye/flare-vm#277]
![FlareVm1](https://user-images.githubusercontent.com/61257522/74891361-b26ec080-533b-11ea-800b-70f785fb50e2.PNG)
![Flarevm2](https://user-images.githubusercontent.com/61257522/74891366-b569b100-533b-11ea-9d64-e96b1dfd0d1f.PNG)

[+] Installing Boxstarter
Chocolatey is going to be downloaded and installed on your machine. If you do not have the .NET Framework Version 4 or g
reater, that will also be downloaded and installed.
[+] Installing Boxstarter
Chocolatey is going to be downloaded and installed on your machine. If you do not have the .NET Framework Version 4 or g
reater, that will also be downloaded and installed.
Exception calling "DownloadString" with "1" argument(s): "The underlying connection was closed: An unexpected error occ
urred on a send."
At line:75 char:36
+             iex ($wc.DownloadString <<<< ("https://chocolatey.org/install.ps1"))
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

The term 'cinst' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spell
ing of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:6
+ cinst <<<<  Boxstarter -y --version 2.12.0
    + CategoryInfo          : ObjectNotFound: (cinst:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Import-Module : The specified module 'C:\ProgramData\boxstarter\boxstarter.chocolatey\boxstarter.chocolatey.psd1' was n
ot loaded because no valid module file was found in any module directory.
At line:41 char:22
+         Import-Module <<<<  "$env:ProgramData\boxstarter\boxstarter.chocolatey\boxstarter.chocolatey.psd1" -Force
    + CategoryInfo          : ResourceUnavailable: (C:\ProgramData\...chocolatey.psd1:String) [Import-Module], FileNot
   FoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

Boxstarter Module Installer completed
Property 'RebootOk' cannot be found on this object; make sure it exists and is settable.
At C:\Users\RothBoth\Desktop\flare-vm-master\flare-vm-master\install.ps1:252 char:13
+ $Boxstarter. <<<< RebootOk = $true # Allow reboots?
    + CategoryInfo          : InvalidOperation: (RebootOk:String) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

Property 'NoPassword' cannot be found on this object; make sure it exists and is settable.
At C:\Users\RothBoth\Desktop\flare-vm-master\flare-vm-master\install.ps1:253 char:13
+ $Boxstarter. <<<< NoPassword = $false # Is this a machine with no login password?
    + CategoryInfo          : InvalidOperation: (NoPassword:String) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

Property 'AutoLogin' cannot be found on this object; make sure it exists and is settable.
At C:\Users\RothBoth\Desktop\flare-vm-master\flare-vm-master\install.ps1:254 char:13
+ $Boxstarter. <<<< AutoLogin = $true # Save my password securely and auto-login after a reboot
    + CategoryInfo          : InvalidOperation: (AutoLogin:String) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The term 'Set-BoxstarterConfig' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\RothBoth\Desktop\flare-vm-master\flare-vm-master\install.ps1:255 char:21
+ Set-BoxstarterConfig <<<<  -NugetSources "https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2"
    + CategoryInfo          : ObjectNotFound: (Set-BoxstarterConfig:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

The term 'Disable-MicrosoftUpdate' is not recognized as the name of a cmdlet, function, script file, or operable progra
m. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\RothBoth\Desktop\flare-vm-master\flare-vm-master\install.ps1:258 char:24
+ Disable-MicrosoftUpdate <<<<
    + CategoryInfo          : ObjectNotFound: (Disable-MicrosoftUpdate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

The term 'choco' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spell
ing of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:6
+ choco <<<<  sources add -n=fireeye -s https://www.myget.org/F/fireeye/api/v2 --priority 1
    + CategoryInfo          : ObjectNotFound: (choco:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

The term 'choco' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spell
ing of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:6
+ choco <<<<  upgrade -y vcredist-all.flare
    + CategoryInfo          : ObjectNotFound: (choco:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

The term 'choco' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spell
ing of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:6
+ choco <<<<  install -y powershell
    + CategoryInfo          : ObjectNotFound: (choco:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

The term 'refreshenv' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:11
+ refreshenv <<<<
    + CategoryInfo          : ObjectNotFound: (refreshenv:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

[+] Performing normal installation...
The term 'choco' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spell
ing of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\RothBoth\Desktop\flare-vm-master\flare-vm-master\install.ps1:289 char:8
+   choco <<<<  upgrade -y -f common.fireeye
    + CategoryInfo          : ObjectNotFound: (choco:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

The term 'Install-BoxStarterPackage' is not recognized as the name of a cmdlet, function, script file, or operable prog
ram. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\RothBoth\Desktop\flare-vm-master\flare-vm-master\install.ps1:290 char:28
+   Install-BoxStarterPackage <<<<  -PackageName flarevm.installer.flare -Credential $cred
    + CategoryInfo          : ObjectNotFound: (Install-BoxStarterPackage:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by MalwareMechanic** [comment]
@DaronBaron What version of Windows are you using?

**Comment by DaronBaron** [comment]
@MalwareMechanic I am using windows 7 32bit

**Comment by Seurgeon** [comment]
Same issue here

running win 7 x64, latest everything

**Comment by DaronBaron** [comment]
> 
> 
> Same issue here
> 
> running win 7 x64, latest everything
> 
> Powershell 5.1
> .Net 4.7.2
> 
> ![grafik](https://user-images.githubusercontent.com/44359294/75092552-2518af80-5579-11ea-8f8f-7234ed4beafb.png)
> 
> EDIT:
> Fixed it by installing chocolatey manually, then running the install script afterwards.

Yeah so far everything is working I updated my powershell and installed chocolatey manually.

**Comment by MalwareMechanic** [comment]
@DaronBaron We've updated packages and made sure to note that there are new requirements with Win7:

Chocolatey now requires PowerShell v3 (or higher) and .NET 4.0 (or higher) due to recent upgrades to TLS 1.2. Please ensure .NET 4+ and PowerShell v3+ are installed prior to attempting FLARE VM installation. Below are links to download .NET 4.5 and WMF 5.1 (PowerShell 5.1).

.NET 4.5 https://www.microsoft.com/en-us/download/details.aspx?id=30653
WMF 5.1 https://www.microsoft.com/en-us/download/details.aspx?id=54616

Please let me know if you are continuing to have issues

**Comment by DaronBaron** [comment]
> 
> 
> @DaronBaron We've updated packages and made sure to note that there are new requirements with Win7:
> 
> Chocolatey now requires PowerShell v3 (or higher) and .NET 4.0 (or higher) due to recent upgrades to TLS 1.2. Please ensure .NET 4+ and PowerShell v3+ are installed prior to attempting FLARE VM installation. Below are links to download .NET 4.5 and WMF 5.1 (PowerShell 5.1).
> 
> .NET 4.5 https://www.microsoft.com/en-us/download/details.aspx?id=30653
> WMF 5.1 https://www.microsoft.com/en-us/download/details.aspx?id=54616
> 
> Please let me know if you are continuing to have issues

I was able to fix my issue by installing chocolatey by itself first then running the script.

**Comment by BiteFoo** [comment]
> > @DaronBaron We've updated packages and made sure to note that there are new requirements with Win7:
> > Chocolatey now requires PowerShell v3 (or higher) and .NET 4.0 (or higher) due to recent upgrades to TLS 1.2. Please ensure .NET 4+ and PowerShell v3+ are installed prior to attempting FLARE VM installation. Below are links to download .NET 4.5 and WMF 5.1 (PowerShell 5.1).
> > .NET 4.5 https://www.microsoft.com/en-us/download/details.aspx?id=30653
> > WMF 5.1 https://www.microsoft.com/en-us/download/details.aspx?id=54616
> > Please let me know if you are continuing to have issues
> 
> I was able to fix my issue by installing chocolatey by itself first then running the script.

It's works for me,thx :D
