### ISSUE TITLE
WinDbg Shortcut Interrupts Install

### ISSUE THREAD

**Issue by osardar** [fireeye/flare-vm#30]
Windows attempts to locate a `windbg.exe` shortcut during the install, and this pauses the install process unless the user selects an option from the dialog box.  Smooth install otherwise!

![windbg](https://user-images.githubusercontent.com/6282041/30918748-6ad8a64e-a36d-11e7-8573-cccfb5ed500c.png)

**Comment by iphelix** [comment]
Can you give me a bit more details please. Was this an x86 version of Windows by any chance?

**Comment by osardar** [comment]
This was a Windows 7 x86 install.  I made a fresh VM with 4 cores & 2GB RAM, and the first thing I did upon logging in was start the install process.

**Comment by Chiggins** [comment]
I had the same issue as @osardar when I ran the script last night. Different system settings, but same Windows 7 x86.

**Comment by iphelix** [comment]
Thanks folks, it must be an x86 issue, will look into that.

**Comment by htnhan** [comment]
New windbg package fixes this issue. Tested on windows 7 x86
