### ISSUE TITLE
Boxstarter installation problem

### ISSUE THREAD

**Issue by LarryCheech** [fireeye/flare-vm#32]
Running  a windows 7 VM and trying to install Flare.

Run boxstarter but get and error "Cannot download application. The application is missing required files"
I have attached the log , any advice?

[CA8I3DC2.log](https://github.com/fireeye/flare-vm/files/1343719/CA8I3DC2.log)

**Comment by LarryCheech** [comment]
I have managed to figure out what I was doing wrong. I was trying to launch the script through firefox. It must be launched through internet explorer as the installation instructions say.

Hope this helps anyone making the same mistake. RTFM!

**Comment by iphelix** [comment]
Weblauncher installation method is unfortunately deprecated. Please try the new installation method in the updated README and reopen if you still have any issues.
