### ISSUE TITLE
Installation script attempts to install Python 3.9 on Windows 7

### ISSUE THREAD

**Issue by shinmai** [fireeye/flare-vm#326]
The installation script downloads and tries to install Python 3.9.0 even if the VM is a Windows 7 installation, where the installation will always fail, as the Python 3.9.0 installer is set to refuse installation on anything below Windows 8.1

Manually installing Python 3.8.6 into C:\Python39 and issuing `cinsts --force libraries.python3.fireeye` will succesfully install the libraries and tools that depend on python3, but it'd be great if the installation script took care of such things automagically.

**Comment by htnhan** [comment]
@shinmai, We just upgrade FLARE-VM to v2.3.4.1 that should limit python version to 3.7.x to work on Windows 7.

**Comment by zaqes** [comment]
This is still an issue for me

```
You have python3 v3.7.2 installed. Version 3.9.1 is available based on your source(s).
python3 not upgraded. An error occurred during installation:
 Updating 'python3 3.7.2' to 'python3 3.9.1' failed. Unable to find versions of 'libraries.python2.fireeye, libraries.py
thon3.fireeye' that are compatible with 'python3 3.9.1'.
python3 package files upgrade completed. Performing other installation steps.
The upgrade of python3 was NOT successful.
python3 not upgraded. An error occurred during installation:
 Updating 'python3 3.7.2' to 'python3 3.9.1' failed. Unable to find versions of 'libraries.python2.fireeye, libraries.py
thon3.fireeye' that are compatible with 'python3 3.9.1'.
```

**Comment by htnhan** [comment]
Hi @zaqes, Sorry I missed this issue.

Currently, on Windows 7, we have to limit python version to 3.7.x. Starting at 3.8, python no longer supports windows 7. There are two options here:

1. Do not update and work with an older version of python. Based on your error message, it says 3.7.2.
2. Use FLARE-VM on Windows 10. We are testing a few more edge cases while attempting to support Windows 10. However, the current install script should *mosty* work on Windows 10 x64. You should still have most of the packages.

**Comment by htnhan** [comment]
Hi @Dobatymo,

Thank you for using FLARE-VM. Recently, I am no longer a member of FireEye/Mandiant and the FLARE-VM development team. Therefore, I am unable to support this issue. However, if Python installation is still an issue, I'd recommend opening a new ticket for the current FLARE-VM development Team.

Nhan
