### ISSUE TITLE
windbg.ollydumpex.flare & windbg.pykd.flare installation failure because of ’Could not find a part of the path‘

### ISSUE THREAD

**Issue by Wesly-Zhang** [fireeye/flare-vm#329]
Hi, Guys
I encounter installation problem related to install windbg.ollydumpex.flare and windbg.pykd.flare on windows 7 sp1 x64. Please see the uploaded screenshot.
![2020-11-16_104731](https://user-images.githubusercontent.com/33350770/99207762-c1669e80-27f9-11eb-9f92-4416e4c954ab.png)
![2020-11-16_104756](https://user-images.githubusercontent.com/33350770/99207771-c4fa2580-27f9-11eb-84ff-808e3e20ce85.png)
I have searched for the issue report but no one have, So Is there a way to solve this problem? please tell me.
Regards.

**Comment by htnhan** [comment]
hi @Wesly-Zhang, we just updated `windbg.flare`. Please try to install `windbg.flare` again, and let us know if you have any issues.
