### ISSUE TITLE
git-credential-winstore not installed. An error occurred during installation:  The operation has timed out.

### ISSUE THREAD

**Issue by MuTouRend** [fireeye/flare-vm#33]
hello
@mwrock  
thanks for your sharing
Follow your tutorial http://boxstarter.org/WebLauncher 
runing     start ......(My Script)......gistfile1.txt
prompt：
Progress: Downloading git.install 2.14.2.20170927... 99%                       
git-credential-winstore not installed. An error occurred during installation:
 The operation has timed out.
git-credential-winstore package files install completed. Performing other instal
lation steps.
The install of git-credential-winstore was NOT successful.
git-credential-winstore not installed. An error occurred during installation:
 The operation has timed out.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - git-credential-winstore (exited 1) - git-credential-winstore not installed. A
n error occurred during installation:
 The operation has timed out.
Chocolatey reported an unsuccessful exit code of 1. See C:\Users\Anonymous\AppDa
ta\Local\Boxstarter\boxstarter.log for details.

。。。

dotpeek not installed. An error occurred during installation:
 Unable to resolve dependency 'resharper-platform (= 109.0.20170921.82506)'.
dotpeek package files install completed. Performing other installation steps.
The install of dotpeek was NOT successful.
dotpeek not installed. An error occurred during installation:
 Unable to resolve dependency 'resharper-platform (= 109.0.20170921.82506)'.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - dotpeek (exited 1) - dotpeek not installed. An error occurred during installa
tion:
 Unable to resolve dependency 'resharper-platform (= 109.0.20170921.82506)'.
Chocolatey reported an unsuccessful exit code of 1. See C:\Users\Anonymous\AppDa
ta\Local\Boxstarter\boxstarter.log for details.

What do i need to do?  ：D
Thanks

**Comment by iphelix** [comment]
Weblauncher installation method is unfortunately deprecated. Please try the new installation method in the updated README and reopen if you still have any issues.

**Comment by MuTouRend** [comment]
@iphelix
I have got it
Try to see some related commands about chocolate
So that more convenient for my work
Thanks
