### ISSUE TITLE
googlechrome.fireeye issue on install

### ISSUE THREAD

**Issue by zaqes** [fireeye/flare-vm#338]
```
googlechrome.fireeye v2020.11.25.0
googlechrome.fireeye package files upgrade completed. Performing other installation steps.
WARNING: 'C:\Program Files\Google\Chrome\Application\chrome.exe' does not exist. If it is not created the shortcut will
not be valid.
ERROR: The term 'C:\Program Files\Google\Chrome\Application\chrome.exe' is not recognized as the name of a cmdlet, funct
ion, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path i
s correct and try again.
The upgrade of googlechrome.fireeye was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\googlechrome.fireeye\tools\chocolateyInstall.ps1'.
 See log for details.
```

Looks like Chrome 32-bit is installed and not 64-bit that this is looking for.

**Comment by htnhan** [comment]
Hi @zaqes,  I believe we have an update for this. Please give it another shot and let me know if you still have issues.

**Comment by zaqes** [comment]
This still an issue I'm afraid.

You have googlechrome.fireeye v2019.03.14.8 installed. Version 2020.11.25.0 is available based on your source(s).
Progress: Downloading googlechrome.fireeye 2020.11.25.0... 100%

googlechrome.fireeye v2020.11.25.0
googlechrome.fireeye package files upgrade completed. Performing other installation steps.
WARNING: 'C:\Program Files\Google\Chrome\Application\chrome.exe' does not exist. If it is not created the shortcut will
not be valid.
ERROR: The term 'C:\Program Files\Google\Chrome\Application\chrome.exe' is not recognized as the name of a cmdlet, funct
ion, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path i
s correct and try again.
The upgrade of googlechrome.fireeye was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\googlechrome.fireeye\tools\chocolateyInstall.ps1'.

**Comment by htnhan** [comment]
@zaqes,

Can you try uninstalling `googlechrome.fireeye` and `googlechrome` packages, then install the latest version of `googlechrome.fireeye`?

**Comment by zaqes** [comment]
That worked, thanks!
