### ISSUE TITLE
Online course Install fail

### ISSUE THREAD

**Issue by Felix1862** [fireeye/flare-vm#345]
I am doing a course and the part that requests to install a package is getting status code 404: This is the install cmd
At the  prompt,typeInstall-BoxstarterPackage-PackageNamehttps://raw.githubusercontent.com/fireeye/flare-vm/master/flarevm_malware.ps1
![image](https://user-images.githubusercontent.com/51448701/104829011-540dd300-5867-11eb-9f6e-8c2d92ec54b3.png)
What could be the problem?

**Comment by htnhan** [comment]
Hi @Felix1862, it looks like you are using the instruction from an older version. Please follow the following updated installation method: https://www.fireeye.com/blog/threat-research/2018/11/flare-vm-update.html or check out the `README.md` in the repo.

**Comment by Felix1862** [comment]
Thank you ever
