### ISSUE TITLE
x64dbg.py.flare updated download URL

### ISSUE THREAD

**Issue by crahan** [fireeye/flare-vm#367]
The download URL for the `x64dbg.py.flare` package has changed and is now available from:

```
url = 'https://ci.appveyor.com/api/buildjobs/g8562v6jb6udimi2/artifacts/release.zip'
checksum = 'e03a895c0038141c5951ee38665642ab64212135ddae5cefab0fe084c87a46c8'
checksumType = 'sha256'
```

If the Flare and Fireeye Chocolatey package definitions are available on GitHub somewhere I can submit a pull request as well. Please let me know the proper repo to submit the pull request to.

**Comment by MalwareMechanic** [comment]
Thanks for finding a viable URL! I've updated the associated package. Stay tuned in the coming weeks, we're looking to add package definitions to GH to make community additions much easier!
