### ISSUE TITLE
dnSpy-x86 points to 64bit binary instead of 32 bit.

### ISSUE THREAD

**Issue by psanjay679** [fireeye/flare-vm#374]
actual location of dnSpy-x86 binary (32bit) is C:\Program Files (x86)\dnspy-x86. Bit it points to "C:\Program Files (x86)\dnspy\dnSpy.exe" which loads 64bit binary. Attaching screenshot 
![Screenshot 2021-05-27 at 8 44 17 PM](https://user-images.githubusercontent.com/13630320/119852187-b15c1400-bf2c-11eb-9572-fb7139c889ba.png)

**Comment by MalwareMechanic** [comment]
Updated, pleased reinstall the package via:
> choco upgrade dnspy.flare
