### ISSUE TITLE
Add YARA Windows Binaries

### ISSUE THREAD

**Issue by voteblake** [fireeye/flare-vm#39]
YARA is basically the only tool I've found myself needing to add to flare-vm.

Windows installation instructions here: https://yara.readthedocs.io/en/v3.6.0/gettingstarted.html#installing-on-windows

I can take a stab at this, success not guaranteed.

**Comment by cryps1s** [comment]
I'm working on a project similar to flare-vm, and in the process of building the appropriate choco package. Would love to collaborate on getting some of these packages fixed up and included.

**Comment by voteblake** [comment]
@cryps1s that's great to hear. I started to look at the choco documentation on building a new package, but it isn't something I had experience with. If you finish that please link it to this issue - I'd appreciate it.

**Comment by cryps1s** [comment]
Can confirm that you can get the python-yara library pretty easily: 

- choco install vcbuildtools -y
- choco install yara-python -source python -y

This will install: 
- DotNet 4.5.1
- VC Build Tools 2015
- Yara-Python Library

Haven't done testing in-depth, but it seems to function okay.
