### ISSUE TITLE
Tool(s) suggestion

### ISSUE THREAD

**Issue by doomedraven** [fireeye/flare-vm#4]
Would be nice to also have those tools in repo :)

* [netsetman](http://www.netsetman.com/es/freeware)
* [pestudio](https://winitor.com/binaries.html)

**Comment by Chiggins** [comment]
I was also going to suggest Immunity Debugger and the mona.py addition for
Immunity and WinDbg.

**Comment by doomedraven** [comment]
* [WinAPIOverride] http://jacquelin.potier.free.fr/winapioverride32/ there already SpyMonitor, but as alternative could be good to have it also

**Comment by bernardofsr** [comment]
I think [pestudio](https://www.winitor.com/binaries.html) is a nice tool to add and [RDG](http://www.rdgsoft.net/) is good as alternative to Die.

**Comment by iphelix** [comment]
Added pestudio to the distro. Type "cinst pestudio" on an existing installation to add the tool.
