### ISSUE TITLE
Update pestudio chocolatey package

### ISSUE THREAD

**Issue by cryps1s** [fireeye/flare-vm#41]
It looks like the chocolatey package for pestudio is currently broken. The flare chocolatey package is serving up version 8.66, but the pestudio website (and target url) is serving up version 8.68. As a result, there are checksum mismatches, causing the chocolatey package installation to fail (unless using unsafe parameters).

I've also reached out to the maintainer of the public pestudio package (https://chocolatey.org/packages/PeStudio) to see if he's willing to update and/or open source that project.

**Comment by iphelix** [comment]
Pushed pestudio 8.69
