### ISSUE TITLE
Update blog post to account for deprecated Weblauncher installation method

### ISSUE THREAD

**Issue by wonglkd** [fireeye/flare-vm#44]
It would be great to update the blog post with the new installation method, or at least indicate there that the Weblauncher installation method is deprecated. As a new user, it's natural to head there as the README directs users to the blog post for installation instructions. In the meantime, it would be great to update the README to make this clearer (and shift the Legal Notice to the bottom.) (It took me a while to realise that my installation issues were due to using the old method.) Thanks for the effort taken to put this together!

**Comment by markconover** [comment]
Agreed.  It is not clear that one should NOT use the Weblauncher way which takes forever to finish.  Following the flare-vm github README is the correct and fast way.  All references to the Weblauncher way should be removed or noted that it is deprecated.

**Comment by htnhan** [comment]
Updated: https://www.fireeye.com/blog/threat-research/2018/11/flare-vm-update.html
