### ISSUE TITLE
Installation Issue using .\install.ps1

### ISSUE THREAD

**Issue by SeattleForensics** [fireeye/flare-vm#45]
1 Nov 2017
-Created Win 10 x64 VM + All Windows Updates as of 1 Nov 2017
-Brought it up to version 1709 build 16299.19
-Opened Administrator PowerShell Window
-Copied install.ps1 to C:\Temp
-In PowerShell Window "Set-ExecutionPolicy Unrestricted", chose A for ALL upon prompt
-Ran ".\install.ps1"
-The installation started fine, but upon review of the messages in the PowerShell window, there were several errors.
-The programs that were not installed correctly were:
     PEStudio
     WireShark 2.4.2
     WinPcap_4_1_3.exe
     oletools-0.51.tar.gz
     https://github.com/fireeye/flare-fakenet-ng/archive/master.zip
     https://github.com/fireeye/flare-floss/zipball/master
     https://github.com/fireeye/flare-qdb/zipball/master
-Additionally, many redundant chocolatey directories are being created. An example is the following:  
Failures
 - https://github.com/fireeye/flare-qdb/zipball/master - WindowsError: [Error 206] The filename or extension is too long: 'c:\\users\\flare\\appdata\\local\\temp\\chocolatey\\chocolatey\\chocolatey\\chocolatey\\chocolatey\\chocolatey\\chocolatey\\chocolatey\\chocolatey\\chocolatey\\chocolatey\\chocolatey\\chocolatey\\chocolatey\\chocolatey\\chocolatey\\chocolatey\\chocolatey\\pip-build-ttr99f'

Let me know if there is an email address I can send the entire install log to, if you care to review. Thank you in advance.

**Comment by htnhan** [comment]
Fixed in commit b21e7191c8500633b10c01f7506ca75e184003d9
