### ISSUE TITLE
Confusing FN Icon Behaviour

### ISSUE THREAD

**Issue by cmunky05** [fireeye/flare-vm#46]
I think there is some potential for confusion with the FN icon in the taskbar of the VM. I would expect clicking on the FN icon on the taskbar to start FakeNet. I now know I can run FakeNet by typing fakenet into this window, however new users could be confused by the fakenet.py usage information.

**Comment by iphelix** [comment]
Updated behavior to launch fakenet once you click on the icon instead of displaying help
