### ISSUE TITLE
wireshark can't start missing api-ms-win-crt-runtime-I1-1-0.dll 

### ISSUE THREAD

**Issue by andyrat33** [fireeye/flare-vm#51]
wireshark can't start missing api-ms-win-crt-runtime-I1-1-0.dll this is still an issue on a 64bit Windows 7 install.

**Comment by htnhan** [comment]
@andyrat33 

I just tested FlareVM installation today on windows 7 x64 and windows 7 x86. In both cases, wireshark works property and is capturing traffic. I am closing this issue out. If you still have  problem with wireshark, please create a new issue with extra information like windows build number, screenshots, etc so we can to reproduce it.
