### ISSUE TITLE
A of tools have not been installed after running script

### ISSUE THREAD

**Issue by ChrisDevinePimss** [fireeye/flare-vm#55]
So i made a windows 10 pro vm box.
Installed .net 3.5 feature
Followed the read me instructions in the GitHub for installation.

And most of the listed tools installed but thing such as ida-free never. 

I also found a lot of errors to do with path being to long in your script. 

Might be worth trying to run it yourself on a fresh box or editing the read me... 

But still a great VM all the same thanks

**Comment by htnhan** [comment]
Fixed in commit b21e7191c8500633b10c01f7506ca75e184003d9
