### ISSUE TITLE
Can't use the boxstarter script

### ISSUE THREAD

**Issue by dummys** [fireeye/flare-vm#6]
Hello.

Here is the error on windows 7:

```
Boxstarter: Installing package C:\flarevm_malware.ps1
Boxstarter Version 2.9.27
(c) 2017 Matt Wrock. http://boxstarter.org

Please type CTRL+C or close this window to exit Boxstarter if you do not want to
 risk a reboot during this Boxstarter install.

Boxstarter may need to reboot your system.
Please provide your password so that Boxstarter may automatically log you on.
Your password will be securely stored and encrypted.
Autologon Password:
Autologon Password:
Autologon Password:
Boxstarter: Unable to authenticate password for Windows7_Build\user. Proceeding w
ith autologon disabled
Boxstarter: Disabling Automatic Updates from Windows Update
Boxstarter: Created a temporary package tmp511B.tmp from C:\flarevm_malware.ps1
in C:\Users\user\AppData\Local\Apps\2.0\7KVTCJQ1.JJD\DTY4ZZ18.R87\boxs..tion_6b09
2740f7261cd0_0002.0009_8212bec7b6369c95\BuildPackages
+ Boxstarter starting Calling Chocolatey to install tmp511B.tmp. This may take s
everal minutes to complete...
Installing the following packages:
tmp511B.tmp
By installing you accept licenses for the packages.
[NuGet] Installing 'tmp511B.tmp 1.0.0'.
[NuGet] Successfully installed 'tmp511B.tmp 1.0.0'.

tmp511B.tmp v1.0.0 (forced)
tmp511b.tmp package files install completed. Performing other installation steps
.
ERROR: Missing file specification after redirection operator.
The install of tmp511b.tmp was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\tmp511B.tmp\tools\ChocolateyI
nstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - tmp511b.tmp (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\
tmp511B.tmp\tools\ChocolateyInstall.ps1'.
 See log for details.
+ Boxstarter finished Calling Chocolatey to install tmp511B.tmp. This may take s
everal minutes to complete... 00:00:10.2038717
Boxstarter: Restore Automatic Updates from Windows Update
Type ENTER to exit:
```

**Comment by beyefendi** [comment]
I had similar problem.
I have manually copied the flarevm_malware.ps1 into C:\, it solved the problem.

**Comment by dummys** [comment]
Tested, didnt works

**Comment by doomedraven** [comment]
i had similar issue, just started install.bat in cmd(opened with admin priv8), try that

**Comment by dummys** [comment]
Same problem

**Comment by munoo** [comment]
didnt works ,,

平台版本信息
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 2.0.50727.5420
	System.Deployment.dll 		: 2.0.50727.5420 (Win7SP1.050727-5400)
	mscorwks.dll 			: 2.0.50727.5420 (Win7SP1.050727-5400)
	dfdll.dll 			: 2.0.50727.4927 (NetFXspW7.050727-4900)
	dfshim.dll 			: 4.0.40305.0 (Main.040305-0000)

源
	部署 URL			: file:///C:/Users/user/Desktop/Boxstarter.WebLaunch.application

标识
	部署标识		: Boxstarter.WebLaunch.application, Version=2.9.27.0, Culture=neutral, PublicKeyToken=6b092740f7261cd0, processorArchitecture=msil

应用程序摘要
	* 仅联机应用程序。
	* 设置信任 URL 参数。
错误摘要
	以下是错误摘要，这些错误的详细信息列在该日志的后面。
	* 激活 C:\Users\user\Desktop\Boxstarter.WebLaunch.application 导致异常。 检测到下列失败消息:
		+ 下载 file:///C:/Users/user/Desktop/Application Files/Boxstarter.WebLaunch_2_9_27_0/Boxstarter.WebLaunch.exe.manifest 未成功。
		+ 未能找到路径“C:\Users\user\Desktop\Application Files\Boxstarter.WebLaunch_2_9_27_0\Boxstarter.WebLaunch.exe.manifest”的一部分。
		+ 未能找到路径“C:\Users\user\Desktop\Application Files\Boxstarter.WebLaunch_2_9_27_0\Boxstarter.WebLaunch.exe.manifest”的一部分。
		+ 未能找到路径“C:\Users\user\Desktop\Application Files\Boxstarter.WebLaunch_2_9_27_0\Boxstarter.WebLaunch.exe.manifest”的一部分。

组件存储事务失败摘要
	未检测到任何事务错误。

警告
	执行此操作的过程中未出现任何警告。

操作进度状态
	* [2017/8/3 15:54:14] : 已启动 C:\Users\user\Desktop\Boxstarter.WebLaunch.application 的激活过程。
	* [2017/8/3 15:54:15] : 部署清单处理已成功完成。
	* [2017/8/3 15:54:15] : 已启动应用程序的安装过程。

错误详细信息
	执行此操作期间检测到下列错误。
	* [2017/8/3 15:54:15] System.Deployment.Application.DeploymentDownloadException (未知子类型)
		- 下载 file:///C:/Users/user/Desktop/Application Files/Boxstarter.WebLaunch_2_9_27_0/Boxstarter.WebLaunch.exe.manifest 未成功。
		- 源: System.Deployment
		- 堆栈跟踪:
			在 System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			在 System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			在 System.Deployment.Application.FileDownloader.Download(SubscriptionState subState)
			在 System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			在 System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			在 System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, Uri& appSourceUri, String& appManifestPath)
			在 System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			在 System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			在 System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			在 System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- 内部异常 ---
		System.Net.WebException
		- 未能找到路径“C:\Users\user\Desktop\Application Files\Boxstarter.WebLaunch_2_9_27_0\Boxstarter.WebLaunch.exe.manifest”的一部分。
		- 源: System
		- 堆栈跟踪:
			在 System.Net.FileWebRequest.EndGetResponse(IAsyncResult asyncResult)
			在 System.Net.FileWebRequest.GetResponse()
			在 System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
		--- 内部异常 ---
		System.Net.WebException
		- 未能找到路径“C:\Users\user\Desktop\Application Files\Boxstarter.WebLaunch_2_9_27_0\Boxstarter.WebLaunch.exe.manifest”的一部分。
		- 源: System
		- 堆栈跟踪:
			在 System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
			在 System.Net.FileWebRequest.GetResponseCallback(Object state)
		--- 内部异常 ---
		System.IO.DirectoryNotFoundException
		- 未能找到路径“C:\Users\user\Desktop\Application Files\Boxstarter.WebLaunch_2_9_27_0\Boxstarter.WebLaunch.exe.manifest”的一部分。
		- 源: mscorlib
		- 堆栈跟踪:
			在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
			在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
			在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
			在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
			在 System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
			在 System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)

组件存储事务详细信息
	没有可用的事务信息。

**Comment by dummys** [comment]
so ?

**Comment by dummys** [comment]
nobody looks the repo ?

**Comment by iphelix** [comment]
Weblauncher installation method is unfortunately deprecated. Please try the new installation method in the updated README and reopen if you still have any issues.

**Comment by stacklikemind** [comment]
Can you please update the deprecation information here too?
https://www.fireeye.com/blog/threat-research/2017/07/flare-vm-the-windows-malware.html

It would have saved me some time knowing this. 
Thanks for your great work guys!
