### ISSUE TITLE
Feedback that will hopefully help the install go even smoother ...

### ISSUE THREAD

**Issue by jfx41** [fireeye/flare-vm#61]
Greetings and salutations!

I just wanted to give a little bit of feedback on my experience installing FLARE.  I am installing it on a Windows 7 x64 VM under ESXi  6.5.

These are really piddly and I only bring them up in the hopes it'll make the process a tiny bit smoother than it already is.

The [blog post](https://www.fireeye.com/blog/threat-research/2017/07/flare-vm-the-windows-malware.html) with the link to the [boxstarter image](http://boxstarter.org/package/url?https://raw.githubusercontent.com/fireeye/flare-vm/master/flarevm_malware.ps1) does not display properly in IE and the boxstarter link is covered up.

I ended up having to manually enter in the URL for the process to kick off.  I know fixing the website to render properly in an old version of IE is just silly, but maybe include a shortened URL for it as well?

I got the feeling that boxstarter expects IE to be the default browser.  In my case, it wasn't, Chrome was.  So while the installer was running I changed the default back to IE.  I'm not certain, but I think something may have gotten missed in the period before I got suspicious about the default browser.  

It's just a hunch I had, so I thought I might throw it out there in case that assumption about IE is true.  

I might revert my snapshot again and run the process over again and see if it goes off without any scary red errors like this one (there were a few, but I couldn't screenshot them fast enough):

<img width="774" alt="screen shot 2018-01-16 at 11 58 35 pm" src="https://user-images.githubusercontent.com/695316/35026838-5399dc40-fb1b-11e7-9579-64033b3cf9ef.png">

I'm really looking forward to using this awesome VM you guys put together.  I hope this feedback helps.

**Comment by jfx41** [comment]
So, just to follow up on this, I did revert my VM back and attempted the install again.  Here is what I did:

1. I created a shortened URL for the boxstarter: [https://goo.gl/1YwiRF](https://goo.gl/1YwiRF)
2. I set the default browser back to IE.
3. I opened IE and put in the shortened URL.
4. I ran the program and entered my password.
5. I watched as it seamlessly installed everything.  I don't think I saw any scary red.  I am going to assume my hunch about IE was right.
6. I rejoiced in your awesomeness.

Thanks for all your hard work!

**Comment by iphelix** [comment]
Hi jfx41,

The web installer was unfortunately deprecated by the box starter team. There is a new installer script which make the installation a lot smoother but requires you to place it on the target host. Check out updated Readme for instructions on how to use it.

Sincerely,
Peter

**Comment by jfx41** [comment]
Peter,

Thank you very much!  I got excited by finding the blog post and jumped on it. I'll revert my snapshot and do it again. 

Thank you for the reply and at of your hard work.
