### ISSUE TITLE
Upgrade IDA Free to 7.0

### ISSUE THREAD

**Issue by htnhan** [fireeye/flare-vm#66]

**Comment by anwilli5** [comment]
Note: IDA Free 7.0 will only disassemble 64-bit binaries, so it'd be great to continue to install the older IDA Free version as well for as long as it's still available (to enable 32-bit binary disassembly.)

**Comment by htnhan** [comment]
Thank you @anwilli5, I will make sure both versions are installed and available.

**Comment by viyatb** [comment]
@anwilli5 @htnhan IDA Free 7.0 is able to disassemble 32-bit binaries regardless of the warning on the splash page.
