### ISSUE TITLE
Windows Defender

### ISSUE THREAD

**Issue by anwilli5** [fireeye/flare-vm#69]
After I ran the FLARE VM setup scripts on a new Windows 10 Enterprise VM, many of the malware samples under Practical Malware Analysis Labs / BinaryCollection got quarantined by Windows Defender.

It'd be nice to have the scripts automatically disable Windows Defender, or at least just add a reminder in the documentation about disabling it before running the install scripts.

Thanks, and thank you to the team for putting together a great, easy to setup Malware RE disto!

**Comment by htnhan** [comment]
@anwilli5 

Thank you for using Flare VM. Disabling Windows Defender has been mentioned in #8 among disabling other security features on windows. We are working on it.
