### ISSUE TITLE
Bug with Cutter flareVM launcher

### ISSUE THREAD

**Issue by Maijin** [fireeye/flare-vm#72]
Hi,

I noticed that when launching cutter, it launches the following:

```
C:\Windows\System32\cmd.exe /K "C:\ProgramData\chocolatey\lib\cutter.flare\tools\cutter\cutter.exe"
```

Not really sure why flareVM is doing that though but this is causing an issue when Cutter is looking for the path of certain files:

![image](https://user-images.githubusercontent.com/1408600/37477414-f4c28af2-2877-11e8-8604-7370bcaee96f.png)

This works when I launch directly without cmd  "C:\ProgramData\chocolatey\lib\cutter.flare\tools\cutter\cutter.exe" instead:

![image](https://user-images.githubusercontent.com/1408600/37477530-301115ec-2878-11e8-8912-3a35da9e134b.png)

This also breaks analysis, description of opcodes, function argument and many core-feature of the tool etc.

**Comment by htnhan** [comment]
@Maijin  A new package is pushed to fixed this. The issue is with the start path of the shortcut. Please let me know if you still have the same bug with cutter.
