### ISSUE TITLE
Add a procedure to update (including new package)

### ISSUE THREAD

**Issue by Maijin** [fireeye/flare-vm#73]
Currently the update only concern update of current installed package, it should also describe how to update the flare-vm when new packages/programs are installed. 
(git pull + which script should be relaunch)

**Comment by htnhan** [comment]
@Maijin We will add an update script to update flare-vm, not just installed packages.

**Comment by Maijin** [comment]
great 👍

**Comment by tankbusta** [comment]
I tried updating my VM by running `flarevm_malware.ps1` again but I noticed some unexpected errors when running some of the frozenpy tools like floss and fakenet-ng. I attached a screenshot of the vague "failed to create process" error shown (this was from an elevated shell).
 
<img width="420" alt="screen shot 2018-05-09 at 09 38 19" src="https://user-images.githubusercontent.com/592749/39824985-edc6cc1a-536d-11e8-826b-c49256df0e10.png">

**Comment by htnhan** [comment]
@all A new version of FLARE VM is available. It should properly support update. Please perform a fresh installation. Then, for new releases, simply do cup all, or cup flarevm.installer.flare.
