### ISSUE TITLE
.NET Framework 4.0.3019 required for Choco

### ISSUE THREAD

**Issue by odzhan** [fireeye/flare-vm#75]
The installation script fails to execute successfully without .NET Framework 4.0.3019 installed prior to running.

**Comment by doomedraven** [comment]
https://chocolatey.org/install

```
Requirements

    Windows 7+ / Windows Server 2003+
    PowerShell v2+
    .NET Framework 4+ (the installation will attempt to install .NET 4.0 if you do not have it installed)
```

**Comment by odzhan** [comment]
Yes, .NET 4.0.3019 is a dependency, but the flareon script doesn't install it before attempting to use choco. That's why the install.ps1 script failed for me until I installed .NET 4.0. If the machine already has choco installed, then it doesn't matter. dotpeek also requires .NET 4.5 which must be installed after .NET 4.0.
