### ISSUE TITLE
Exe Files being automatically deleted

### ISSUE THREAD

**Issue by yakamoz147** [fireeye/flare-vm#82]
Hello,

I just reinstalled a VM and Flare-Vm for the second time fresh only to notice that exe-files in that machine are beeing automatically deleted after some time (randomly). Is it some kind of a test that there already seems to be an active malware? I'm just starting to learn so Im not sure what is happening but its only happening in this VM and also I didnt execute any files yet. Also it happens again and again when I reset the VM to a previous snapshot... Any insights?

**Comment by htnhan** [comment]
@yakamoz147  please let us know specifically which files are deleted.

**Comment by yakamoz147** [comment]
Slowly but surely all the PMA Lab Files for now. I havent noticed any other files dissappearing for now but I'm still checking...

**Comment by yakamoz147** [comment]
I am very embarrased. I just used Process Monitor to find out which Process is deleting files and found it to be MsMpEnd.exe which means it's Windows Defender if I'm right? Sorry about this!

**Comment by turbosmurfen** [comment]
I need to leave this here. Malwarebytes (In main) is blocking connections to different hosts that the installation is downloading. So It could happen to other software which block "hack" tools sites. So when installing flare-vm turn off your anti malware/virus before. Then later you could activate the protection.
