### ISSUE TITLE
Error using install script

### ISSUE THREAD

**Issue by dummys** [fireeye/flare-vm#83]
Hi on windows 10x64 I got this error:

[ * ] Installing Boxstarter
Welcome to the Boxstarter Module installer!
Chocolatey installed, Installing Boxstarter Modules.
Chocolatey v0.10.9
Installing the following packages:
Boxstarter
By installing you accept licenses for the packages.
[NuGet] The underlying connection was closed: An unexpected error occurred on a send.
Boxstarter not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Version was specified as '2.10.3'. It is possible that version
 does not exist for 'Boxstarter' at the source specified.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - Boxstarter - Boxstarter not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Version was specified as '2.10.3'. It is possible that version
 does not exist for 'Boxstarter' at the source specified.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.
Import-Module : The specified module 'C:\ProgramData\boxstarter\boxstarter.chocolatey\boxstarter.chocolatey.psd1' was
not loaded because no valid module file was found in any module directory.
At line:41 char:9
+         Import-Module "$env:ProgramData\boxstarter\boxstarter.chocola ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\ProgramData\...chocolatey.psd1:String) [Import-Module], FileNot
   FoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by htnhan** [comment]
@dummys  Thank you for reporting this. I will look into this.

**Comment by htnhan** [comment]
@dummys  We recently have a major update for FLARE VM with better support for windows 10. Do you mind testing again to see if you still have the same issue?

**Comment by dummys** [comment]
Ok I will test and come back to you !

**Comment by htnhan** [comment]
Recent FLARE VM update is not backward compatible. Please do a fresh install since we made many changes to the packages names and installation process.

**Comment by dummys** [comment]
ok is there a way to reinstall without reinstalling windows ? It's very boring to do it.
