### ISSUE TITLE
Add parameter to pass credentials for automated installation

### ISSUE THREAD

**Issue by Wenzel** [fireeye/flare-vm#88]
Hi !

I'm trying to build a set of Packer templates to automatically build and generate FLARE VMs.
https://github.com/Wenzel/packer-flare

The problem i have is the `install.ps1` script, which is prompting for the user to get his credentials.

I would like to pass the user password as a script parameter, allowing me to automate the installation in my provisioner.

Would that be possible ?

I already forked and made an attempt:
https://github.com/Wenzel/flare-vm/blob/master/install.ps1#L32

~~~powershell
$passwd=ConvertTo-SecureString -String "vagrant" -AsPlainText -Force
$cred=New-Object -TypeName "System.Management.Automation.PSCredential" -ArgumentList $env:username, $passwd
~~~

(Update: it works !)
Thanks !

**Comment by htnhan** [comment]
Fixed in 237f87ecb516e06a47a21db00743c369119caf1f
