### ISSUE TITLE
Add CMDER 

### ISSUE THREAD

**Issue by keyzerrezyek** [fireeye/flare-vm#9]
Nice and clean cmdline for both bash/cmd/ps.
http://cmder.net/

**Comment by williballenthin** [comment]
chocolately package exists: https://chocolatey.org/packages/Cmder

**Comment by iphelix** [comment]
Please use chocolatey package if you would like this added.

cinst cmder

to customize your environment.

**Comment by iphelix** [comment]
Ah cool, let me play with it a bit more and survey folks to see if it's popular enough to add to the baseline. Thanks for the heads up!

**Comment by keyzerrezyek** [comment]
I think nobody will argue that cmd.exe leaves a lot to be desired... :)

**Comment by iphelix** [comment]
Hehe, that’s true.

**Comment by iphelix** [comment]
The tools is great, adding it to the default distro.
