### ISSUE TITLE
Add Far Manager

### ISSUE THREAD

**Issue by BenjaminSoelberg** [fireeye/flare-vm#91]
May I suggest to add Far Manager, a free Norton Commander alike tool. Lots of plugins available. Very stable. Quick to use and even has a simple hex/text mode viewer build in as well as a text mode editor. I have used it for years.

-----------

Far Manager is a program for managing files and archives in Windows operating systems. Far Manager works in text mode and provides a simple and intuitive interface for performing most of the necessary actions:

viewing files and directories;
editing, copying and renaming files;
and many other actions.

Homepage: https://www.farmanager.com/index.php?l=en

**Comment by iphelix** [comment]
Are there any additional plugins that you would suggest to include as well?

**Comment by BenjaminSoelberg** [comment]
I would suggest to go with a stock install to start with.

**Comment by htnhan** [comment]
added with bced4d386e18ec321a93a3e1e6d9475a8e46effa
