### ISSUE TITLE
cup all fails to update Python 2.7 due to custom path

### ISSUE THREAD

**Issue by htnhan** [fireeye/flare-vm#97]
If you use the ‘cup all’ command to update the packages it doesn’t work as expected for Python2.7. Unfortunately, the Chocolatey Python2.7 package is configured to install to C:\Python27 instead of where FLAREVM has it installed under C:\Program Files\. So when someone uses ‘cup all’ it will automatically update/install into C:\Python27 instead of updating the existing Python installation, which of course interferes with all the awesome Python scripts your team included in C:\Program Files\Python27\scripts.

**Comment by mr-tz** [comment]
Is this related to https://github.com/fireeye/flare-vm/issues/40? I experienced the same issue after an update.

**Comment by htnhan** [comment]
Likely related. I'll close this one and keep #40
